### ISSUE TITLE
When should I dispose the RxMoyaProvider?

### ISSUE THREAD

**Issue by PMExtra** [Moya/Moya#1009]
When should I dispose the RxMoyaProvider?

If I add that to `self.disposeBag`, I guess that will hold until the viewController dismissing.

So if I make many requests in the viewController, that will be very terrible...

**Comment by PMExtra** [comment]
```Swift
Timer.every(5.0.seconds) {
    _ = RxMoyaProvider<MyAPI>.request(.heartbeat).subscribe()
}
```

Is this right? I don't care the response or error. I just want to send a request periodically.

**Comment by gregpardo** [comment]
Wouldn't you do something like this....

```swift
let provider = RxMoyaProvider<MyAPI>()

Timer.every(5.0.seconds)
   .flatMap({ _ in return provider.request(.heartbeat)})
   .switchLatest()
   .subscribe(onNext: { _ in 
      print("thump")
   })
```

**Comment by AndrewSB** [comment]
Great question @PMExtra 😄 

First, you wouldn't be disposing the `RxMoyaProvider` as a whole, you'd dispose a (or a number) of subscriptions created by the `RxMoyaProvider` which represent pending network requests. More of a naming issue, but it could cause a misunderstanding with what you're actually doing.

So you should dispose subscriptions when you're no longer interested in them. In your case, thats when you'd no longer like to send heartbeats to your server.
If you only want to send heartbeats when a specific view controller is alive, then you should add it to the vc's dispose bag, otherwise you should add it to a long living disposeBag, maybe of a class that belongs to your AppDelegate (like your `NetworkManager`, or something like that)

Let us know if you have any other questions about this 👍

**Comment by PMExtra** [comment]
@AndrewSB Thank you much. I think I made a conceptual mistake. The request is retain by subscription instead of provider.
And I think the `Finite sequence` does not need to `addDisposeBag`, they will auto dispose while receiving `.completed` or `.error` message.

I have no problem now, thanks you all.
