### ISSUE TITLE
Does Moya/Alamofire Support Multiple Base URL's?

### ISSUE THREAD

**Issue by camcoding** [Moya/Moya#1028]
I have an IOS app that needs to access a user's home-based server.  If the user is on their home network, the request should happen on their home network (e.g. 192.168.1.x.).  However, if the user is remote, the request should be sent to their static DNS/IP.  Some users use a VPN so I really need my app to connect to the primary and if it fails then fail over to the secondary.

The user enters both local/remote settings inside my app.  I was hoping that Moya/Alamofire could be configured to have a primary and secondary base URL so that if the primary fails the secondary is invoked.

**Comment by pedrovereza** [comment]
Hey @camcoding, take a look at #980. @scottrhoyt gave some ideas on how to change the `baseURL` dynamically

**Comment by camcoding** [comment]
Thank you @pedrovereza.  That #980 does resemble something similar to what I'm trying to accomplish but it's only a portion of what I'm after - but I'll work through it and see if I can come up with a decent solution.

Ideally I'd like to give Moya 2 URL's - one first one would be primary and the other secondary/backup.  If the primary call fails, the secondary would be executed.  These URL's point to the exact same server so everything on the backend is identical - the URL's differ if the user is local/home versus remote.

**Comment by pedrovereza** [comment]
@camcoding My first impression was that you could use the basic logic of #980 to achieve what you need, because in #980 the steps are:

1 - Make a request to a `baseURL`
2 - Extract the next `baseURL` from the response of the first call
3 - Use the extracted url as `baseURL` for the second request

And this could go on for several requests.

For your scenario, I'm assuming you can first try the local home address (which should fail when the user is remote):

1 - Make a request to `baseURL` using the local address
2 - If the request fail, switch `baseURL` to the remote address and make the request again

Once you know where the user is (home vs remote), you could probably store this information in your app and avoid making two requests every time if they are remote, and just make it once a while to check if they changed location.

Does that make sense in your case?

**Comment by camcoding** [comment]
Yep - that's exactly what I'm after - just trying to figure out how to do that Moya-style :-)  

There are many areas of my code where I invoke network calls so I'm trying to figure out a way to abstract the logic away from the code calling the API and have the RxMoyaProvider execute the primary/secondary call "behind the scenes".   For instance, here's a typical call:

`        MyAPI.sharedInstance.provider.request(MyProvider.Programs)
            .subscribe(onNext: { (response) -> Void in
                self.parsePrograms(response: response)
                //   print(response)
            }, onError: { (error) -> Void in
                print(error)
            }).addDisposableTo(bag)`

I suppose I could capture the error, alter the baseURL of the provider, and re-execute the request but I'd have to copy/paste that logic all over the place.

**Comment by pedrovereza** [comment]
@camcoding Can you  write a `CustomProvider` that subclasses `RxMoyaProvider`  and implement the logic in `CustomProvider`? 🤔 

I'm not too familiar with RxSwift, but if this approach is not too complicated (or impossible), you'd get the logic nicely wrapped in a single place :wink:

**Comment by gperdomor** [comment]
In #978 you can see some ideas to have dynamic urls... I go with the subtarget protocol and the dynamic provider... Maybe we can integrate that functionality in 9.0.0... WDYT?

**Comment by AndrewSB** [comment]
Yup, #978 should have a solution, if you're still having issues @camcoding, reopen this and we'd be happy to help 👍
