### ISSUE TITLE
How do you cancel a network request based off of a condition?

### ISSUE THREAD

**Issue by gmoalvarez** [Moya/Moya#1029]
I am using Moya and RxSwift to build out my network stack...really porting it but I am a bit new to the Rx way of thinking and I have a general approach question. 

I am using Realm on the device and am planning on syncing up the data with our API. My plan is:

 User edits on device -> Data is saved on local database -> This update is put on a network queue of some sort (I haven't built this part yet but I am planning on using OperationQueue) and the appropriate Moya request is sent.

Ok, lets say we have the following sequence of events:

**1) User edits or adds item A**
---goes on queue (suppose we don't have network connectivity at this point..or slow)
**2) User edits or adds item A**
---goes on queue

Now....what I would like at this point is to cancel the first request and only send the last one since that has all of the necessary information. I would like to use RxSwift if possible.

Could you please help by offering some suggestions on how I would approach such a problem?

**Comment by AndrewSB** [comment]
Are you implementing an optimistic UI? i.e. you're going to show an update has _succeeded_ before it actually comes back from the network? If so, moving your network requests into a separate queue will make it very hard to tie back server validation/network failures back to the original callee (from my experience, YMMV).

I'd recommend instead when your user edits/adds item A, you do

```swift 
func updateA(newA: AType) -> Observable<AType> {
  return Observable.concat([
    saveDataToRealm(newA),
    saveDataToNetwork(newA)
  ])
}
```

and what will happen is, first your data will be saved to Realm, on completion of that, you'll get a `.next` even from your `updateA()` observable, and simultaneously your network request will kick off. At this point, you can update your UI to be optimistically successful. (hundreds of) Milliseconds later you should get back the second network request, which will show itself is a `.next`and `.complete`, where you can now make the optimistic success an actual success.
Also, if there was an error, you'd be able to handle the error at the callsite, instead of trying to associate it back to the callsite from your queue

There is the chance for a race condition though, but you should be returned the latest model from the network in `updateA()`. So as long as your UI uses that as the source of truth, your user will be able to see the race condition and fix it

**Comment by gmoalvarez** [comment]
Yup I think you are right. That is pretty much what I have been doing but I still have the issue of identifying which changes were made offline and save them somehow to send to the server once a connection has been established. 

Maybe, in your example above, on
```
saveDataToNetwork(newA)
```
if there is an error, I can either:

- Save the request itself to retry once a network has been established
or
- Save the primary key and type of Realm object and have some kind of background process that goes through the list of entities that need updating.

Do any of those approaches sound reasonable?

**Comment by AndrewSB** [comment]
Hmm, yeah, if I understand what you're doing, yes. More or less.

What I would do is just mark that entity as having a pending sync in Realm, (and then have a background process that periodically goes and tries to upload pending syncs), like you said 😄 

If you save that request (in memory) to a list of requests to be retried once the network has been established, you may run into some non deterministic behavior, either by sending the sync multiple times (one from the realm background process, another from the in memory queue waiting for network reconnection), or risk dropping the queue from in memory if the app is quit before you persist to realm.

I'd recommend just going the persistent save + background processing route, and maybe even building a custom `OfflineSync` class that handles all your network requests if your app relies heavily on offline syncing

**Comment by gmoalvarez** [comment]
Yup that is pretty much what I was thinking of doing. Thank you for all of your suggestions. It was very helpful.

**Comment by AndrewSB** [comment]
😄
