### ISSUE TITLE
Change EndpointSampleResponse.networkError associated value to Swift.Error

### ISSUE THREAD

**Issue by Zeeker** [Moya/Moya#1073]
I'm using Moya version 8.0.3.

I think Moya would benefit from changing the type of the associated value of `EndpointSampleResponse.networkError` to `Swift.Error`. Right now it's `NSError`, which makes stubbing more painful than it needs to be.

It's obviously possible to simply cast the error but if Moya truly needs an NSError internally it could do that step internally.

**Comment by BasThomas** [comment]
Can you post an example of your use case? I think - but I can't find it right now - we are using `NSError`s on purpose. Maybe someone of the @Moya/contributors knows or can point to a discussion on that?

If we do indeed want to end up changing this, It'd be awesome if we can take this with us in the `9.0.0` release.

**Comment by Zeeker** [comment]
It's not really a big thing, right now I have to do this:

```swift
EndpointSampleResponse.networkError(MyError.someError as NSError)
```

If `EndpointSampleResponse` would receive a `Swift.Error` directly I could avoid the `as NSError` cast and instead do this:

```swift
EndpointSampleResponse.networkError(MyError.someError)
```

**Comment by sunshinejr** [comment]
I think I was implementing this one and I'm also positive there was a reason for `NSError`, but I don't remember right now and I don't see any downsides, so I think we can try changing it to just an implementation of `Error` type. At least we can do a PR and see what happens. Especially with 9.0.0 version that is in the making. Do you want to take a stab at that, @Zeeker?

**Comment by pedrovereza** [comment]
Possibly related: https://github.com/Moya/Moya/issues/437#issuecomment-198780649 and https://github.com/Moya/Moya/issues/478

**Comment by sunshinejr** [comment]
Oh right, I was talking about this one for sure! Thanks, @pedrovereza. 

However, this is different error here. The problem was with underlying error in request/response, here is a problem with sample response. It is kinda similar problem, because normally this should be a underlying `NSError` (a network error). Now that I think about it, maybe we can go with `MoyaError` here? Moya has an `.underlying` error already, which takes an `NSError` if needed. Although how would we go about custom errors?
