### ISSUE TITLE
Can't build project without crashing after adding Moya with Carthage

### ISSUE THREAD

**Issue by dannymout** [Moya/Moya#1114]
Using Moya 8.0.5 with Carthage.

Recently, when I've tried to get Moya using Carthage, my app will crash when I add Moya and the other dependencies.

This is the error I get:
````
dyld: Library not loaded: @rpath/XCTest.framework/XCTest
  Referenced from: /Users/danny/Library/Developer/CoreSimulator/Devices/6B5A4C41-8CF2-4818-A4B0-B331A1D3C4E9/data/Containers/Bundle/Application/504C3F5A-A3B2-407B-AEF2-7E7E77E9F05F/err.app/Frameworks/libswiftXCTest.dylib
  Reason: image not found
(lldb) 
````

I've tried using `--no-use-binaries` with no luck.

**Comment by pedrovereza** [comment]
Hey @dannymout, I just created a simple project using Moya and Carthage and it's working fine 🤔 
https://github.com/pedrovereza/MoyaCarthage

Can you setup a demo project that recreates the issue you're facing?

**Comment by dannymout** [comment]
@pedrovereza I set up this project: https://github.com/dannymout/MoyaCrash, it crashes on my computer.

**Comment by BasThomas** [comment]
It's been a while since using Carthage, but it seems like @pedrovereza has no Carthage folder, and you do, @dannymout. Any idea what the difference in setup was?

**Comment by pedrovereza** [comment]
@BasThomas I didn't push the Carthage folder on porpuse, as it contains only build artifacts 😄

**Comment by pedrovereza** [comment]
@dannymout I noticed a few things in your project:

* The frameworks for iOS should be under `Linked Frameworks and Libraries` only, not on `Embedded Binaries`
* The scrip that copies frameworks under `Build Phases` is missing
* The actual problem is happening because of the way `RxTest` is being linked. Linking testing frameworks is a bit different than linking "normal" frameworks ([see here](https://github.com/Carthage/Carthage#adding-frameworks-to-unit-tests-or-a-framework))

I'd recommend following the steps in the [Carthage docs](https://github.com/Carthage/Carthage#adding-frameworks-to-an-application) :wink:

**Comment by dannymout** [comment]
@pedrovereza Followed all that, and I get the same error.

Is RxTest a Moya dependency, or can I just not link it at all.

**Comment by pedrovereza** [comment]
@dannymout You don't have to link if you won't use it. The project I created is only linking what's needed for Moya: `Alamofire.framework`, `Moya.framework` and `Result.framework`

**Comment by dannymout** [comment]
I didn't know I could go that barebones. That should fix everything. @pedrovereza

**Comment by pedrovereza** [comment]
@dannymout Awesome, let us know how it goes 🎉

**Comment by pedrovereza** [comment]
@dannymout were you able to get it to work?

**Comment by dannymout** [comment]
@pedrovereza Yes and thank you, should've closed this sooner, been busy with WWDC.
