### ISSUE TITLE
How to implement Network wrapper of request -> response cycle with ReactiveCocoa?

### ISSUE THREAD

**Issue by Marcopohlo** [Moya/Moya#1171]
Hello guys,

so I've discovered this great Library and want to use it with ReactiveCocoa. 

I'm trying to implement Network wrapper based on [this](https://github.com/Moya/Moya/blob/master/docs/Examples/WrappingInAdapter.md). However I'm unable to proceed. 

First of all I don't even know if those callbacks are the right choice when dealing with ReactiveCocoa. 
Also it says "_Invalid conversion from throwing function of type '(_) throws -> ()' to non-throwing function type '(Event<_, _>) -> Void'_"
And lastly it says "_use of unresolved identifier 'error'_"

What am I doing wrong?

```swift
import Moya
import SwiftyJSON

struct Network {
    
    static let endpointClosure = { (target: MyService) -> Endpoint<MyService> in
        let defaultEndpoint = MoyaProvider.defaultEndpointMapping(for: target)
        
        // Sign all non-authenticating requests
        switch target {
        case .authenticate:
            return defaultEndpoint
        default:
            return defaultEndpoint.adding(newHTTPHeaderFields: ["Token": GlobalAppStorage.authToken])
        }
    }
    
    static let provider = ReactiveSwiftMoyaProvider<MyService>(endpointClosure: endpointClosure)
    
    static func request(
        target: MyService,
        success successCallback: @escaping (JSON) -> Void,
        error errorCallback: @escaping (_ statusCode: Int) -> Void,
        failure failureCallback: @escaping (MoyaError) -> Void
        ) {
        provider.request(target).retry(upTo: 2).start() { event in
            switch event {
            case let .value(response):
                do {
                    try response.filterSuccessfulStatusCodes()
                    let json = try JSON(response.mapJSON())
                    successCallback(json!)
                }
                catch error {
                    errorCallback(error)
                }
            case let .failed(error):
                failureCallback(error)
            default:
                break
            }
        }
    }
}
```

**Comment by sunshinejr** [comment]
Hey @Marcopohlo, thanks for the issue! 

Basically, what you want to accomplish doesn't really benefit from the fact you are using reactive provider (besides `retry`). You are transforming your `Signal` to a simple closure callback, where the whole point is to keep this object and make plethora of operations on it. If you want `ReactiveSwift` just for Moya and this adapter, I'd say that you should leave it and do something similar to our [current wrapper](https://github.com/Moya/Moya/blob/master/docs/Examples/WrappingInAdapter.md) (without reactive provider).

Although if you are using ReactiveSwift in your project quite extensively, I would suggest you take a different approach, a more reactive one. Please take a look at our [subclassing example](https://github.com/Moya/Moya/blob/master/docs/Examples/SubclassingProvider.md). This is in RxSwift, but conversion to ReactiveSwift should be pretty simple (`RxMoyaProvider` -> `ReactiveSwiftMoyaProvider`, `Observable` -> `Signal`/`SignalProducer`). 

This is also a subclassing example, but you could go with composition instead (especially because in Moya 9.0.0 we are deprecating reactive providers). A simple pseudo-code that would cover what I have in mind would be:

```swift
final class Networking<T: TargetType> {

    let provider: ReactiveSwiftMoyaProvider<T>
    
    init(provider: ReactiveSwiftMoyaProvider<T>) {
        self.provider = provider
    }
    
    func request(target: T) -> SignalProducer<Response, MoyaError> {
        return provider.request(target)
    }
}
```

Also, if you'd do it, you could make a PR with example using ReactiveSwift - we would gladly take that one 😄 

Let me know if you still have some questions about it :)

**Comment by Marcopohlo** [comment]
First of all, thank you for your answer, I really appreciate it. 

Yes, the project is using ReactiveCocoa everywhere, but I'm quite new to that, but I felt making classic closures out of SignalProducers was not the best idea. So thank you for clarification on that. 

Will try to implement composition and will post PR when ready and good.

Also I may bother you with a few questions here and there, if that's okay.

Thank you for now :)

**Comment by sunshinejr** [comment]
No problem, happy to assist! Did you have some more troubles there, @Marcopohlo?
