### ISSUE TITLE
How can i use Webview's Delegate didFailLoadWithError with Controller content Moya

### ISSUE THREAD

**Issue by zichenJack** [Moya/Moya#1176]
When i use moya In a Controller that content webview
I was never reveice webview fail delegate

```
func webView(_ webView: UIWebView, didFailLoadWithError error: Error) {
        print("加载失败")
    }
```
It error's log 
```
WebViewController.swift:349:68: 'Error' is ambiguous for type lookup in this context
WebViewController.swift:349:68: Found this candidate (Swift.Error)
WebViewController.swift:349:68: Found this candidate (Moya.Error)
```
If i was write Swity.Error ,The delegate never run when webview load fail

so,How can I do for this problem?

**Comment by sunshinejr** [comment]
Hey @zichenJack. Thanks for detailed explanation. This should be a fairly easy fix. As error says, the problem is because both `Moya` and `Swift` use type name `Error`. Having imported `Moya`, the compiler just gets confused as to what type do you really want. To make sure it gets a `Swift` one, just prefix the type with `Swift.`, like `Swift.Error`:

```swift
    func webView(_ webView: UIWebView, didFailLoadWithError error: Swift.Error) {
        print("UIWebView Error")
    }
```

and it should resolve the issue. I've tested it on a clean project using Moya 8.0.5 and Swift 3.1 and it worked correctly, but if you still encounter the issue, please let us know! 👍
