### ISSUE TITLE
Check documentation for parameters/encoding/task migration.

### ISSUE THREAD

**Issue by sunshinejr** [Moya/Moya#1205]
We might need to check if our documentation is up-to-date (in branch 9.0.0-dev) with the changes to parameters/parameterEncoding/task from #1147. 

If someone is up for this task, please assign yourself so we won't dup our work. Cheers! 😉

**Comment by SD10** [comment]
Documention Affected:
- [ ]  [Basic.md](https://github.com/Moya/Moya/blob/4207ead20f3da590194b1be1d64d409316c083cf/docs/Examples/Basic.md)
- [ ] [Targets.md](https://github.com/Moya/Moya/blob/4207ead20f3da590194b1be1d64d409316c083cf/docs/Targets.md)
- [ ] [Endpoints.md](https://github.com/Moya/Moya/blob/4207ead20f3da590194b1be1d64d409316c083cf/docs/Endpoints.md)
- [ ] [ArraysAsRootContainer.md](https://github.com/Moya/Moya/blob/aa33a0466d7333516691b3e5212c5acb41990928/docs/Examples/ArrayAsRootContainer.md)
- [ ] [Providers.md](https://github.com/Moya/Moya/blob/4207ead20f3da590194b1be1d64d409316c083cf/docs/Providers.md)
- [ ] [OptionalParameters.md](https://github.com/Moya/Moya/blob/4207ead20f3da590194b1be1d64d409316c083cf/docs/Examples/OptionalParameters.md)
- [ ] [Assets.md](https://github.com/Moya/Moya/blob/aa33a0466d7333516691b3e5212c5acb41990928/docs/Examples/Assets.md)

It's important to know that a great deal of these has already been taken care of in #1147 so that should be the basis for which docs still need updating. 

If I can check any of these off the list when I have time I will.

**Comment by sunshinejr** [comment]
This is covered by #1256. Closing this one, thanks for the list, @SD10! 👍
