### ISSUE TITLE
Multipart aways set content-type to multipart/form-data

### ISSUE THREAD

**Issue by JeanVinge** [Moya/Moya#1235]
The problem ocurs on version 8.0.5 and 9.0.0-alpha1

```swift

    var headers: [String : String]? {
        
        return ["Content-Type": "image/jpeg"]
    }

    var task: Task {
        
        switch self {
        case .image( let image), .profileImage(let image):
            
            guard let reducedImage = UIImageJPEGRepresentation(image, 0.2) else {
                fatalError("Cant parse to data")
            }
            
            let multipart = MultipartFormData.init(provider: .data(reducedImage), name: "image", fileName: "image.jpeg", mimeType: "image/jpeg")
            
            let list = [multipart]
            return .upload(.multipart(list))
        }
    }
```

when i make the request the content-type changes to multipart/form-data, i have tried to use endpointClousre, but always have the same result the content-type changes to multipart/form-data

**Comment by sunshinejr** [comment]
Hey @JeanVinge, thanks for the issue!

This is actually how multipart file uploads are encoded (details [here](https://www.w3.org/TR/html5/forms.html#multipart/form-data-encoding-algorithm)). And even if it weren't, we can't change it really as Alamofire (our dependency for doing network requests) does it for us [here](https://github.com/Alamofire/Alamofire/blob/5bd458ca09a57fb2999772745d6438585f5140a7/Source/SessionManager.swift#L666) - just before sending the upload request and after our request setup (thus changing the request in Moya won't do anything).

Let me know if you have more questions around this topic!

**Comment by CainLuo** [comment]
Moya: V14.0.0
iOS 13
Xcode 11.5

Is there no way for Moya to modify the Alamofire MultipartFormData contentType? I have an operation to upload an image to the OSS server, but since the contentType is "multipart/form-data; Boundary =\(self. Boundary)", the network request API of Moya had to be abandoned, and the original Swift method was changed as a temporary solution.

**Comment by sunshinejr** [comment]
@CainLuo Can you explain more the use-case you have? Is it uploading a single file, multiple files, files with data (e.g. string? if so, is it in URL or body?). Would help with making the best choice for you.

But in general, in case you only have a file to upload then you can use `upload..` functions instead of `multipartUpload`. If you, however, need to do a multipart upload (files + data), then I don't think there is a way to change the content-type since that's how http parser identifies how to parse content of the request.

**Comment by CainLuo** [comment]
@sunshinejr I'm really sorry for the late reply. I just uploaded a single Image file, which should be in the body of the request. Since Ali Cloud's OSS is set to only support [content-type: Application/ JSON], it needs to be modified.

**Comment by sunshinejr** [comment]
@CainLuo in that case you shouldn't need to use `multipartUpload` task type and use `uploadFile` instead. Can you give it a try?
