### ISSUE TITLE
[Question] New Moya 9.0.0 has different implementation for retryWhen

### ISSUE THREAD

**Issue by alfian0** [Moya/Moya#1280]
On my App I implement retryWhen for refresh token. If return error 401 will force to logout.

Recently I updated moya version from 8.0.5 to 9.0.0, as I know to create retryWhen we extend ObservableType, on moya 9.0.0 not return observable but 

> PrimitiveSequence<SingleTrait, Response>

How to solve that issue ? Thanks for the response 😬

**Comment by AndrewSB** [comment]
The simple fix would just be to add an `.asObservable()` before you `retryWhen`. The reason we switched to a `Single` over an `Observable` was because [RxSwift's new Single trait](https://github.com/ReactiveX/RxSwift/blob/master/Documentation/Traits.md#single) modeled a network request better than a more permissive Observable

**Comment by alfian0** [comment]
Oh I see, good ...thanks @AndrewSB

**Comment by pedrovereza** [comment]
Closing the issue as it seems like @AndrewSB was able to help. 
Feel free to reopen this issue or create a new one if you have more questions, @alfian0 😉
