### ISSUE TITLE
How to generate header parameter depending on request's content type of multipart form data request?

### ISSUE THREAD

**Issue by Nikolaev** [Moya/Moya#1305]
Hello.
I'm using Moya 8.0.5

I need to generate authorization header parameter depending on request's content type.
Request is sending parameters as multipart form data.
Content type's boundary is generating by Alamofire, but Moya doesn't provides abbility to modify request when content-type is set.
Plugin's method "prepare" is calling before generating boundary. As well as "requestClosure".

Is there is any way to achive this?

**Comment by sunshinejr** [comment]
Hey @Nikolaev, this one is tricky. Because we don't really provide a way of doing that in our core. It seems like your only chance would be to subclass `SessionManager` and override multipart upload function, as the content-type is set right before the request, [here](https://github.com/Alamofire/Alamofire/blob/c8a4d3a910bcfd53b9b855463495b8200ca80fd6/Source/SessionManager.swift#L666). Then you would have to pass your own manager as a parameter to `MoyaProvider`.

However, there is another way. If you can find something different than content-type header to depend on, you could create your `endpointClosure` or `requestClosure` to handle it. Maybe you can switch on `Task` type in `endpointClosure` to detect if it's a multipart upload?

Looking forward to hear your implementation in this one!

**Comment by Nikolaev** [comment]
Thank you for reply @sunshinejr !

Eventually i decide to implement my own uploader of multipart data using URLSession.
Subclassing SessionManager is not good idea because in that case my code will have dependency on Alamofire future changes. That will increase cost of code maintance.
And I can't force backend developers to change the type of authentification (sadly). 
So, own implementation is the best solution for me.

Anyway I still use Moya for all the other network requests. Moya is very good! I like the way it works and the way it progress!
