### ISSUE TITLE
URLEncoding differs from Alamofire's URLEncoding 

### ISSUE THREAD

**Issue by wassimseif** [Moya/Moya#1309]
Sending the same request using bare alamofire & Moya/RxSwift yields to different parameters encoding 
First Here's how i'm sending the request using Moya/RxSwift
```
 provider.rx.request(.login(username: "email@example.com",password: "123456",languagID: "8"))
            .subscribe { event in
                switch event {
                case let .success(response):
                    print(response)
                case let .error(error):
                    print(error)
                }
```
With API Target Type being 
```
  public var path: String {
        switch  self  {
        case .login(let username,let  password, let languagID):
            return "login"
        }
    }
    public var task: Task {
        switch self {
        case let .login(username: username  , password: password  , languagID: languageId):
            return .requestParameters(parameters: [
                "username" : username,
                "password" : password,
                "language_id" : languageId
                ], encoding: URLEncoding.default)
        }
    }
    
```
Using Charles to debug the network calls i get this parameter encoding 
![screen shot 2017-09-25 at 3 15 33 pm](https://user-images.githubusercontent.com/7282773/30808376-8a7ea470-a206-11e7-9ef1-20b54b056ea1.png)

Now Using this code snippet to send the request with bare alamofire 
```
   Alamofire.request(URL(string : "url")!, method: .post, parameters: [
            "email" : "email@example.com",
            "password" : "123456",
            "language_id" : "8"
            ], encoding: URLEncoding.default, headers: nil).responseJSON { (dataResponse ) in

        }
```
This will  yield to this parameter encoding which is the one i want 

![screen shot 2017-09-25 at 3 15 22 pm](https://user-images.githubusercontent.com/7282773/30808439-c65f15d8-a206-11e7-8c35-a3cf7e98b6db.png)

How do i get this encoding using moya ?

**Comment by wassimseif** [comment]
So the problem was that i was sending `["Content-Type": "application/json"]` in the headers, why would that affect the body ?

**Comment by sunshinejr** [comment]
Hey @wassimseif. This is a good question.

First of all, our `URLEncoding` is just a typealias on Alamofire's `URLEncoding`. Thus, these are the same in terms of encoding the parameters. 

What you see on Charles is actually interpreted by `Content-Type` header. The data you send is in fact the same, but the way we/server interpret it depends on Content-Type itself. 

Now to the encoding part: because you have your own `Content-Type` already in the header fields when we encode the request, Alamofire's `URLEncoding` won't add the Content-Type they usually do for this type of encoding, which is `application/x-www-form-urlencoded` (more on this matter [here](https://github.com/Alamofire/Alamofire/blob/c8a4d3a910bcfd53b9b855463495b8200ca80fd6/Source/ParameterEncoding.swift#L139)). This results in your data being formatted for `URLEncoding` where your `Content-Type` says that you encoded it for JSON = your endpoint can't resolve it correctly.

Please let me know if it is clear for you or you have any more questions around this topic. Cheers!
