### ISSUE TITLE
RxMoya & ReactiveMoya tests are using deprecated providers

### ISSUE THREAD

**Issue by SD10** [Moya/Moya#1312]
I noticed that our unit tests are running using the `RxMoyaProvider` and `ReactiveSwiftMoyaProvider` that are marked as deprecated in Moya `v9.0.0`. I'm just curious if this is intentional.

**Comment by BasThomas** [comment]
No; they should use the current implementation.

**Comment by sunshinejr** [comment]
@SD10 We changed the tests as well, I don't see where is `RxMoyaProvider` used in tests, but if it is, we should change it. I left some tests for `ReactiveSwiftMoyaProvider` because there were some specific tests with subclassing that could be still valuable before we remove reactive providers.

But, indeed, I found [one place](https://github.com/Moya/Moya/blob/2d182bf7320c67195d77203810f7c334685001fe/Tests/MoyaProviderIntegrationTests.swift#L254) when we have `ReactiveSwiftMoyaProvider` where we probably don't need to.

**Comment by SD10** [comment]
Great, thanks for clarifying. Are we going to remove these in Moya `10.0`? I assume we only leave things deprecated for 1 major version?

**Comment by SD10** [comment]
@sunshinejr I can submit a PR removing these if you'd like. They're blocking my fun ☹️ 

Some other things:
1. Are these two tests identical? [Test One](https://github.com/Moya/Moya/blob/master/Tests/MoyaProvider%2BReactiveSpec.swift#L48) and [Test Two](https://github.com/Moya/Moya/blob/master/Tests/MoyaProvider%2BReactiveSpec.swift#L140).

 I can remove both if so. Just want to make sure we're not missing something.

2. What's the replacement for the `stubScheduler` property of `ReactiveSwiftMoyaProvider`? 

Are we requiring that users override the `stubRequest` method of `MoyaProvider` to use a scheduler?

**Comment by sunshinejr** [comment]
Sure, go ahead @SD10!

1. Right, seems like these are the same.
2. Currently we don't have a replacement easy to build, one of the ways should be subclassing the MoyaProvider as you've said. We were hoping that if the request for this feature is big, we would come up with something easier, but seems like it is not 😄

**Comment by sunshinejr** [comment]
@SD10 if you are working on that, could you change the name of `MoyaProviderRx` class in tests to `MoyaProviderRxSpec` as it is for the rest of it (really bugs me off but I don't want to overlap your work).

**Comment by SD10** [comment]
Yes I've made that change and closing this in favor of the PR @ #1320
