### ISSUE TITLE
Add CodeBeat integration to Moya

### ISSUE THREAD

**Issue by SD10** [Moya/Moya#1411]
Check out [CodeBeat](https://github.com/marketplace/codebeat)

I think it could be a valuable tool to assist us in code review. I think the feature I like the most is the duplicated code warnings. 

Some of the other measurements you really have to take with a grain of salt. However, I think we have the ability to customize the requirements to our liking. Personally, I have not tried that feature.

**Comment by SD10** [comment]
This is an evaluation I did on my fork (I don't know if you all can view it):
https://codebeat.co/projects/github-com-sd10-moya-master

**Comment by AndrewSB** [comment]
This looks interesting @SD10. Does it show up as a GitHub comment on Pull Requests? Do you know of any repos using it where we can see what it looks like?

I'd be down to switch to something like codebeat instead of what we have - Codecov. I feel as if I've always looked at that comment as noise. Codebeat looks more actionable to me from the dashboard I saw
