### ISSUE TITLE
[Enhancement] Customize the localizedDescription for MoyaErrors for user facing. 

### ISSUE THREAD

**Issue by levibostian** [Moya/Moya#1437]
Moya/RxSwift version 10.0.0. 

Here is some sample code for an average app of mine:

```swift
return moyaProvider.rx.request(MultiTarget(FooService.loginUser(facebookAccessToken: facebookAccessToken)))
    .filterSuccessfulStatusCodes()
    .mapObject(FacebookLoginResponseVo.self)
```

The key part to look at here is the `.filterSuccessfulStatusCodes()` call.

When I develop an app, I have the following assumptions:

* The app could call my API and return back a 500 error if my API is down. 
* The app could have a spotty network connection and fail the API request. 
* The device could be offline and the network request will fail. 
* The app performed an API call, got a 401, I need to have the user re-login. 
* The app performed an API call, got a 400, I need to be alerted because there is a bug with the app. I need to tell the user there is an issue, instead of the app crashing without telling the user there is an issue. 

The above is a list of assumptions that myself as well as a majority of the apps of the world have. I feel that is safe to say. 

Now, here is my issue. 

The function call, `.filterSuccessfulStatusCodes()` returns an instance of `MoyaError.statusCode`. In my app error handler function in the case that a MoyaError.statusCode error is thrown, I am displaying the error message to the user:

```swift
let humanReadableErrorMessage = error.localizedDescription
// Show humanReadableErrorMessage to user somehow in the UI. 
```

When I get the description for the error, my users are presented with this type of error message, "Status code didn't fall within the given range." [from source](https://github.com/Moya/Moya/blob/master/Sources/Moya/MoyaError.swift#L66). I do not feel that this error message is useful to the user. I don't want to display that to them. 

If my app has a bug in it mapping JSON. I don't want to show my users, "Failed to map data to JSON." as an error message. I would rather send myself an alert via my crash reporter and give the user a message such as, "Sorry, there has been an issue with the app. The team has been notified. Try again soon.". 

---

To try and resolve this issue and return more human readable error messages specific to my app, I created [this library](https://github.com/levibostian/lucid). It allows me to set human readable error messages to send for all the different error types that can happen in my app. 

This library is fine and dandy, but there are ways it could be better:
* Because of the API of Moya, you must get the more human readable error message after the request completion handler has been called. The task cannot be accomplished via a Moya plugin. This makes the library kinda hacky to get working. I am simply taking the result's `MoyaError` and doing, "is the MoyaError an error with the Internet connection? If so, return this message..." kinda code. It would be nicer if this type of error processing would be available functionality in Moya. 
* Boilerplate code. I need to *remember* for each and every API call in my app to call `processErrors()` (to call the Lucid code) or my library code will not run and I run the risk of showing my users the not-super-useful error messages and not getting alerted when an error has happened. Remembering to call one of the `.filterStatusCode()` functions makes sense to do for every API call but that's hard enough to remember which causes bugs. 

---

What I am trying to get at here, is that from my experience while building my [Lucid library](https://github.com/levibostian/lucid) to enhance Moya errors for my apps, I feel that this functionality is a "common sense" type of enhancement to this library. 

Why? Because every app could throw a 500, have a bad network connection, have an unexpected http error code, or any other assumption in my list above and many other assumptions. This seems like basic functionality each app would require and if it's as simple as being able to edit the `MoyaError`'s description in the Moya code at run-time, that would make the library much more useful for the typical app as well as not requiring this library. 

Thank you so much for your time. I love Moya. Thank you for the consideration.

**Comment by SD10** [comment]
Hey @levibostian,
Thanks for taking the time to write this up 👍. 

I just want to clarify: Are you suggesting we make the `localizedDescription` more readable in a sense that the error message will be displayed in an `UIAlertController` to the users of the application?

If so, these errors are not meant to be displayed to users, they're for the programmer to debug the app. An error message requires a very specific client-side implementation.

**Comment by AndrewSB** [comment]
@levibostian serious props on the repo, it looks like a lot of work went into it!! 


Let me tell you how I handle these assumptions when I work

> The app could call my API and return back a 500 error if my API is down.

when I 500, 2 things happen.
1. A user alert that says "Uh oh, there looks like there was some problem with your network, try again" happens
2. My backend fires an alert that an engineer can look at and potentially fix.

> The app could have a spotty network connection and fail the API request.

Nope! I use a provider that only hits the network if the device has internet connection

> The device could be offline and the network request will fail.

Nope! I use a provider that only hits the network if the device has internet connection

> The app performed an API call, got a 401, I need to have the user re-login.

Nope! I use http://github.com/AndrewSB/Expirable, so I know if my user fail to auth before the request is sent.

> The app performed an API call, got a 400, I need to be alerted because there is a bug with the app. I need to tell the user there is an issue, instead of the app crashing without telling the user there is an issue.

This is legitimate, this would get through everything and result in the same "Uh oh, try again popup", where I'd include the `error.localizedDescription` if it exists.
This would be an actual programmer error on my part, probably. The way I get around this is by unit & integration testing


So overall, to respond to

> Doing what I am doing with the Lucid library seems like the recommended method, is that safe to say?

Somewhat...
Your first step would be to reduce the kinds of errors your networking layer can throw, and then catch those errors. 
Also, Lucid creates issues because it isn't localized. For example, lets say someone in Japan is using my app. `NSError.localizedDescription`s are translated to the user's `NSLocale`, that way if my request 5xxs and I need to show an error message, if I use the `error.localizedDescription` I'll get something relevant in Japanese (assuming Alamofire/NSURLSession/the callee that raises the NSError had it translated). So by catching and rethrowing a non localized error message, you may be reducing your user-friendliness

**Comment by AndrewSB** [comment]
I missed your question, I'm sorry. To respond:


> Because of the API of Moya, you must get the more human readable error message after the request completion handler has been called. The task cannot be accomplished via a Moya plugin. This makes the library kinda hacky to get working. I am simply taking the result's MoyaError and doing, "is the MoyaError an error with the Internet connection? If so, return this message..." kinda code. It would be nicer if this type of error processing would be available functionality in Moya.

I feel as if we already give this kind of functionality from Moya, by parsing the error to see what went wrong

> Boilerplate code. I need to remember for each and every API call in my app to call processErrors() (to call the Lucid code) or my library code will not run and I run the risk of showing my users the not-super-useful error messages and not getting alerted when an error has happened. Remembering to call one of the .filterStatusCode() functions makes sense to do for every API call but that's hard enough to remember which causes bugs.

Let me blow your mind here. Instead of calling `.filterStatusCode()` on a per-response basis, you could use a common `request` function that will do all of the filtering and even the error parsing just once!  I usually use a custom wrapper of Moya (called `Networking` in https://github.com/Moya/Moya/issues/748#issuecomment-257692175), and inside `Networking.request`, I handle filtering successful error codes, and even something similar to what your Lucid does in the next line (using `.catchError(parseMoyaError)`)

**Comment by levibostian** [comment]
Thanks for all the help, @AndrewSB. I appreciate the time very much. 

I will close this issue and continue to use Lucid. It seems that is the best option. Great discussion!
