### ISSUE TITLE
Release 10.0.1

### ISSUE THREAD

**Issue by SD10** [Moya/Moya#1471]
I think we should do a minor release with some of the bugfixes that are now on `master` because I don't see us having a new major version for some time:

### Fixed
- Fix a bug that `Decodable` mapping to object other than Array and Dictionary in a key path cause crash. 
- Fixed a bug with missing Content-Type header when using `.requestJSONEncodable`.
- Fixed linker settings, enabling RxMoya and ReactiveMoya to be used in app extensions.
- Fixed carthage OS X not targeting 10.10.

I'm not sure if #1470 is something we would want to include in this as well. Let me know me know what you guys think.

**Comment by BasThomas** [comment]
Yep, don't see a reason why not 👍

**Comment by sunshinejr** [comment]
@SD10 good idea, was about to make a similar thread 😄 

About bumping ReactiveSwift version and our release process - I tend to think about Moya/ReactiveSwift as both, Moya and ReactiveSwift codebases, combined. This is due to the fact that if you want to use Moya with newer ReactiveSwift version, you need to migrate your _**whole codebase**_ beforehand. Therefore we probably have to release Moya 11 to support ReactiveSwift 3.

There is also Carthage integration that is broken, seems like nobody fixed it yet. I might take a stab at it, but it probably could go as 10.0.2, where all of these we could release faster in 10.0.1.

Let me know how do you feel about it :)

**Comment by SD10** [comment]
@sunshinejr I think putting the upgrade to ReactiveSwift 3.0 is fine, but then we may want 11.0 to be a lot lighter than usual because a few people are already asking about this.

I noticed a lot of issues around Carthage lately as well. I need to reduce the technical knowledge debt in this area because I’m useless on the subject 😅 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sunshinejr** [comment]
Yeah, we will probably release a lot lighter version than 9 or 10.

**Comment by sunshinejr** [comment]
Okay, I think we should move forward with the patch release. @SD10 do you want to take a stab at it? 😉

**Comment by SD10** [comment]
I can give this a try but I may not be able to get to it till the weekend. It's Thanksgiving in the USA today. If anyone can do it before then feel free 😃

**Comment by sunshinejr** [comment]
Oh, no worries, @SD10. I'm gonna release it hopefully today 😉

**Comment by sunshinejr** [comment]
<img width="576" alt="zrzut ekranu 2017-11-23 o 20 14 56" src="https://user-images.githubusercontent.com/5232779/33186613-0d7af2c2-d08b-11e7-832b-7caefd70bc80.png">

🎉

**Comment by lucas34** [comment]
Can we build the frameworks with latest Swift and upload the zip in the release note ? So carthage can checkout the binaries directly
