### ISSUE TITLE
Enable Danger's prose plugin

### ISSUE THREAD

**Issue by AndrewSB** [Moya/Moya#1560]
I think it would be awesome to enable Danger's prose stuff on at least our docs, if nothing else. Maybe the commit message as well.
To enable to prose plugin, go check out http://danger.systems/ruby/, and scroll down to the prose plugin. It will probably just be an edit in our Dangerfile

Also, forcing commit messages to be <72 characters seems like a good idea to me. I dont know how the rest of the contributors feel about this, so we can debate this change if need be 😛

**Comment by BasThomas** [comment]
Regarding commit messages: how would we enforce that? Fail a pull request if any of the commit messages exceed it? Seems a bit much. Maybe just add a warning if, but I lean towards not doing anything there.

**Comment by SD10** [comment]
I’m fine with adding a tool to fix spelling errors in documentation, however, I’m against any rules surrounding git. 

The reason is it I believe it would discourage contributors and increase the barrier of entry to the project. I already have difficulty explaining the concept of rebasing to some people. Having them revert or modify the git history for a character limitation seems like a nightmare 😐

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by AndrewSB** [comment]
Yup, you're totally right @SD10. I was being more pedantic because I just found tpope's style guide and was trying to up my git commit game.

Let's say no to the commit message length, but yes to prose.
