### ISSUE TITLE
Problems using the 'headers' property

### ISSUE THREAD

**Issue by sasojadrovski** [Moya/Moya#1582]
**Moya version: 11.0.0**

First of all I would like to thank you for your amazing work! Using Moya is a pleasure 😊 

I have noticed a strange behavior when adding custom header fields using the `var headers: [String: String]?` property.

More precisely, the following code produces a `Moya.Error error 6` i.e. a `NSURLErrorDomain Code=-1005` error when trying to make a request, i.e. when trying to modify the http headers:

```swift
var headers: [String: String]? {
  var httpHeaders = [
    "deviceid": SecureStorage.shared.uniqueDeviceId,
    "useragent": "iPhone"
  ]
  if let token = SecureStorage.shared.tokenWithBearer {
    httpHeaders["аuthorization"] = token
  }
  return httpHeaders
}
```

whilst the following code does not produce any error:

```swift
var headers: [String: String]? {
  return [
    "deviceid": SecureStorage.shared.uniqueDeviceId,
    "useragent": "iPhone",
    "authorization": SecureStorage.shared.tokenWithBearer ?? ""
  ]
}
```

Previously there were no issues with the first approach and appending an additional header field (like `httpHeaders["аuthorization"] = token`) did not cause any problems.

I would like to hear your thoughts about this strange issue. Could this be related to #1549?

Cheers,
Sasho

**Comment by SD10** [comment]
Hey @sasojadrovski, I don't believe this is related to #1549. That issue is only regarding using both a custom `endpointClosure` and `PluginType`s with a MoyaProvider.

Do you have a custom `endpointClosure` or are you using any plugins with this provider? That modify the `headers` of course.

It looks like `NSURLErrorDomain Code=-1005` is regarding a lost network connection. A lot of StackOverflow posts recommend restarting the simulator (if you are using one).

**Comment by sasojadrovski** [comment]
Hey @SD10,

Thank you very much for the prompt reply!

No, I do not have a custom `endpointClosure` nor any plugins. I am intentionally using the default `MoyaProvider` (wanted to eliminate anything that might modify the `headers`).

I have also tried restarting and reseting the simulator and I have also built and run the application on a device. Unfortunately that did not resolve the issue.

**Comment by sunshinejr** [comment]
Hey @sasojadrovski. The only difference I see in these two snippets of code is that in the working code you _always_ send `Authorization` header even if it's not there. If it's not it, then there must be something in Swift itself, because Moya just gets the dictionary of headers that is passed to Alamofire. Not sure what though, as creating dictionary by appending/initialization shouldn't have any difference. You could also check [this thread on SO](https://stackoverflow.com/a/25996971/2340462).

**Comment by sasojadrovski** [comment]
Hey @sunshinejr,

Thanks for getting back to me regarding this issue/question. 

Yes, I also thought that this must be somehow related to Swift, but what was bothering me was that the code from the first example worked fine for Moya 10. 

Maybe changing the snippet to something like:
```swift
var headers: [String: String]? {
  var httpHeaders: [String: String] = [:]
  httpHeaders["deviceid"] = SecureStorage.shared.uniqueDeviceId
  httpHeaders["useragent"] = "iPhone"
  httpHeaders["authorization"] = SecureStorage.shared.tokenWithBearer
  return httpHeaders
}
```
would overcome this issue. However, utilizing Moya's `AccessTokenAuthorizable` protocol for handling authorization is a much better approach than the one mentioned above, so this issue can be closed for now :)

Thank you very much for discussing this and trying to figure out an answer. I really appreciate it. Keep up the great work! 👍 

Best Regards,
Sasho
