### ISSUE TITLE
Ambiguous reference to member 'map(_:atKeyPath:using:failsOnEmptyData:) 

### ISSUE THREAD

**Issue by canny09** [Moya/Moya#1626]
I wrote a ``Single`` extension in Swift 3 like this, and it work fine.
```Swift
extension Single {
    // json -> model
    func mapModel<T: HandyJSON>(type: T.Type) -> Single<T> {
        // Error Message: Ambiguous reference to member 'map(_:atKeyPath:using:failsOnEmptyData:)'
        return self.map { response -> T in 
            
            let jsonDict = response as? [String : Any]
            guard let model = T.deserialize(from: jsonDict, designatedPath: "data") else {
                throw BlockyError.unKnown
            }
            return model
        } as! Single<T>
    }
}
```
But today, I convert the project to Swift 4, and then get a error message in above by complier. 
Why does it can't recognize the ``map<R>(_ transform:)`` function?
How to deal it?

I use cocoa pods 
```
pod 'RxSwift',    '~> 4.0.0-rc.0'
pod 'RxCocoa',    '~> 4.0.0-rc.0'
```

**Comment by sunshinejr** [comment]
Hey @canny09. I'll need more informations to help you resolve the issue:

1. What version of Moya do you use?
1. Are you sure that `map<R>(_ transform:)` is a method that Moya had before? I can't recall it but maybe my memory is failing me 😅 
1. Can you tell me if you are using additional CocoaPods, for mapping specifically? `ObjectMapper` or `ModelMapper` or any other? If yes, please provide me `Podfile.lock` if possible.

**Comment by canny09** [comment]
@sunshinejr 
😅 I pod the Moya by ``pod 'Moya/RxSwift', '~> 11.0'`` , just update today.
😅 Sorry, my mistake. The method is ``RxSwift``..
😅 I use the [HandyJSON](https://github.com/alibaba/HandyJSON) for mapping json to model

Maybe I should open the issue in RxSwift 😅

**Comment by sunshinejr** [comment]
Oh, so now you are facing a problem with Swift, rather than with RxSwift or Moya... I'll try to give you some hints on how you could try to solve it, as I don't see nothing in particular on the first sight.

Swift is not the best at giving you a precise errors in this situation, that's why I always try to extract the code to a playground if possible to check if the inner code is working without the Rx part. in your case I would try to check if I could write a function and see if it works:
```
    func transform<T>(response: Response) -> T {
        let jsonDict = response as? [String : Any]
        guard let model = T.deserialize(from: jsonDict, designatedPath: "data") else {
            throw BlockyError.unKnown
        }
        return model
    }
```
If it doesn't, you have a better error right in front of you. If it does work, however, there is a problem up the chain. Then I would check if the `Single` extension without the whole `map` transformation works.

```
extension Single {
    func mapModel<T: HandyJSON>(type: T.Type) -> Single<T> {
        return Single.just(T.deserialize(from: jsonDict, designatedPath: "data"))
    }
}
```
The same situation here, if it doesn't work you know where to dig. If it works, then it's probably a typo somewhere or maybe you need an explicit parameter names or explicit return types somewhere. Really not an easy fight.

If you can't find it, let us know, maybe try to build an example project where it happens and someone will for sure try to help you.
