### ISSUE TITLE
How to pass complex Array/Dict in MultipartFormData?

### ISSUE THREAD

**Issue by kaleemozitech** [Moya/Moya#1658]
`                  
   
![screen shot 2018-04-30 at 7 20 19 pm](https://user-images.githubusercontent.com/32861273/39432300-8915caea-4cac-11e8-95f4-3ea4035e2c8e.png)

```swift
dict["area_ids"] = areas

dict["others"] = otherAreas

let odata = try! JSONSerialization.data(withJSONObject: dict, options: .prettyPrinted)

let o26 = MultipartFormData(provider: .data(odata), name: "areas")`
```

i am trying to pass form data Using MultipartFormData 
but i am getting error from server as parameter `area_ids` not passed to the server

**Comment by sunshinejr** [comment]
Hey @kaleemozitech, this is a tough one because there might be many factors involved.

1. Type of your `dict`. Do you have your dictionary typed as `[String: Any]` or `[String: String]`? Additionally, what are `areas`? Is this a `[String]` or `[Int]`? Make sure you are passing the types right.
1. `.prettyPrinted` option for data serialization. This adds some additional space to the encoded data, maybe your server doesn't accept it at all? Try replacing `.prettyPrinted` with `[]`:
```swift
let data = try! JSONSerialization.data(withJSONObject: dict, options: [])
```
1. What headers are you supposed to pass to the server? Is it really `multipart/form-data`? Do you override your headers somewhere? This also can be the reason that your server cannot decode your parameters well.

I think these are the biggest ones that come to my mind right now. If none of these help, let me know and we will try to figure it out. Server logs and more code would be appreciated.
