### ISSUE TITLE
when param is array request as formdata , the key will auto use [] at last.i need have not [].

### ISSUE THREAD

**Issue by freemub-ios-syb** [Moya/Moya#1675]

**Comment by sunshinejr** [comment]
Hey @freemub-ios-syb, I'm sorry but I don't think I understand what is the problem here. Could you be more specific about the problem? 

The best way would be to show a log of requests/reponses (see [this doc](https://github.com/Moya/Moya/blob/master/docs/Plugins.md#logging) about logging) and then explain what you were trying to achieve instead of what you've got.
