### ISSUE TITLE
What is the real minimum deployment target?

### ISSUE THREAD

**Issue by ivensdenner** [Moya/Moya#1772]
I'm updating my app to Swift 4.2 (currently it is using Swift 4.0) but I'm getting an error in Moya-ObjectMapper that, according to the cocoapods error message, it's related to Moya.

I'm getting the error:

```ruby
[!] CocoaPods could not find compatible versions for pod "Moya":
  In Podfile:
    Moya-ObjectMapper/RxSwift (= 2.7) was resolved to 2.7, which depends on
      Moya-ObjectMapper/Core (= 2.7) was resolved to 2.7, which depends on
        Moya (~> 11)

Specs satisfying the `Moya (~> 11)` dependency were found, but they required a higher minimum deployment target.
```

The Moya.podspec says that the minimum deployment target for iOS is 8.0. Ours is 9.0, yet I'm getting this error. The minimum deployment target is really 8.0?

Theses are the versions I'm trying to install:

```ruby
pod 'Moya/RxSwift', '12.0.1'
pod 'Moya-ObjectMapper/RxSwift', '2.7'
```

I'm using cocoapods version 1.5.3 and Xcode 10.1

Thanks in advance :)

**Comment by pedrovereza** [comment]
Hey @ivensdenner, I don't think it covers the entire issue here, but it seems like your `Podfile` has unmeetable versions.

`Moya-ObjectMapper` has `Moya` version defined as `~> 11` (see [here](https://github.com/bmoliveira/Moya-ObjectMapper/blob/master/Moya-ObjectMapper.podspec#L25)), meaning it will take from Moya 11.0 up to 12, but not including 12 (so basically it will take up until Moya 11.0.2, which was our last 11.x release). Which means the highest version of Moya that can be installed is 11.0.2, but you `Podfile` still requires 12.0.1 😬 (more in [CocoaPods docs](https://guides.cocoapods.org/using/the-podfile.html#specifying-pod-versions))

So in order to use Moya-ObjectMapper and Moya 12, Moya-ObjectMapper needs to release a new version supporting Moya 12.

Does that make sense?

**Comment by ivensdenner** [comment]
Oh, I see. I didn't know that `~>` doesn't include the next major version. I think this is the problem :).

So I'll have to wait a new version of Moya-ObjectMapper to update Moya.

Thanks for the help @pedrovereza :)
