### ISSUE TITLE
Content-Type : form-data, format of request is 'data:{deviceId:1}'

### ISSUE THREAD

**Issue by v2kb2l** [Moya/Moya#1809]
![screen shot 2019-02-15 at 11 42 38 pm](https://user-images.githubusercontent.com/1422663/52875863-6d89da00-317b-11e9-83c3-24fbb1e97221.png)

My api accept data in format 
ContentType: form-data
request: 
**data: {deviceid: 1}**
I am not able to call the api in Moya.

Can any one tell which parameterEncoding used to get response.

The code will automatically get its syntax highlighted, and doesn't need to be indented 4 spaces to be shown as code.

I tried in below 2 methods:
            let data = [deviceid: 1]
  1)           return .requestParameters(parameters: data, encoding: URLEncoding.default)
 2) return .requestParameters(parameters: data, encoding: JSONEncoding.default)

**Comment by sunshinejr** [comment]
Hey @v2kb2l, sorry for the late response. You probably figured this out already, so I'll take my time and try to answer with some more details about which encoding you should use. Let's start with the `ParameterEncoding` itself and what it is for.

`ParameterEncoding` was introduced to help with encoding parameters that _you send_ to the server. Basically your server can accept your parameters in multiple ways, with classics like **URL** (https://server.com/endpoint?param1=1&param2=2), **body** (the params are not visible in the URL anymore, but are encoded in the request body) or **multipart encoding**, used for e.g. mixing file uploads with passing normal parameters as well. This means that `ParameterEncoding` is not really associated with the response, but rather the request itself.

Now, about your question. As I can see, you say that your server accepts **multipart/form-data** encoding for that particular request. Setting aside if it's a good usage of multipart encoding, you should use our `Task.uploadMultipart([MultipartData])` case instead of your normal `requestParameters`. If, however, that doesn't work as well, you would have to ask someone from the server to help you out as there might be some custom encoding used.

Let me know if this was helpful or if you've figured it out and we can close the issue. Have a good day!
