### ISSUE TITLE
func didReceive(_ result: Result<Moya.Response, MoyaError>, target: TargetType) {} No call

### ISSUE THREAD

**Issue by CDYeah** [Moya/Moya#1840]
Pod 'Moya', '13.0.0'

Xcode10.2.1 Swift5.0

The custom plugin, called the method in the protocol extension, did not call the method in the custom class, is it caused by ‘Result’ in Swift5.0?

**Comment by ntnthien** [comment]
Same here :( I was facing it since Swift Moya 12.0.1

**Comment by sunshinejr** [comment]
Hey @CDYeah @ntnthien. Would you be able to provide an example code that reproduces the issue so I could investigate it further?

**Comment by zhanglichuan** [comment]
I have the same problem. Has anyone solved it yet。
我遇到了同样的问题， 有人解决问题了没

**Comment by zhanglichuan** [comment]
pod 'Moya/RxSwift'

**Comment by zhanglichuan** [comment]
I have the same problem. Has anyone solved it yet。
我遇到了同样的问题， 有人解决问题了没
# Alamofire (4.8.2)、RxSwift 4.5.0、 Moya (13.0.0)、Result (4.1.0)
    pod 'Moya/RxSwift'

**Comment by zhanglichuan** [comment]
@CDYeah  You can try the NetworkActivityPlugin

**Comment by zhanglichuan** [comment]
@CDYeah  I see，You might not have imported Result

please import Result

**Comment by CDYeah** [comment]
Compile failed after import

import Result

**Comment by xwgit2971** [comment]
The custom plugin must `import Result`...  I spent a lot of time at this

**Comment by CDYeah** [comment]
@_exported import Kingfisher

Kingfisher is imported globally, conflicting with import Result

**Comment by sunshinejr** [comment]
I'm sorry you guys are experiencing this problem. #1839 might resolve it in the future.

**Comment by WeMadeCode** [comment]
Why do we need to import Result？

**Comment by deanWombourne** [comment]
@WeMadeCode I was confused by this too! If you don't explicitly import `Result`, it defaults to using Swift's Result type. Your method still compiles because the methods on the two Result types are so similar. It _looks_ (to a human) like we are implementing the protocol but we aren't because the types don't match - the protocol wants Result.Result, you are using Swift.Result. 

The compiler doesn't complain because all the protocol methods are optional :) Though this would be a nice warning for the compiler to output in cases like this . . .
