### ISSUE TITLE
Combine API poll

### ISSUE THREAD

**Issue by sunshinejr** [Moya/Moya#1905]
Hey all! I'm currently implementing the new Combine extension for Moya in #1904 and I'm wondering what API would you all like the most for it.

What do I mean by API? The access to publishers, basically. In our ReactiveSwift/RxSwift extensions we use `reactive` and `rx` namespaces provided by the frameworks (e.g. `provider.rx.request(.zen)`). For Combine however, the API provided by Apple is quite different - they just add new properties with the `publisher` suffix (e.g. `session.dataTaskPublisher(for: url)`).

So for this issue I would like to create "a poll" in which I would love to see what option you favor  the most.

## Option 1 - Use publisher suffix similar to Apple's extensions
This would mean we would add two additional properties to `MoyaProvider`:
```swift
provider.requestPublisher(target)
provider.requestWithProgressPublisher(target)
```

and you would use it like the following:
```swift
provider.requestPublisher(target)
    .sink(receiveValue: { value in
        // ...
    })
```

## Option 2 - Use "publishers" namespace, similar to "rx" and "reactive" we currently have
This would mean we would add a namespace to `MoyaProvider`, called `publishers`, in which we would add two publishers:
```swift
provider.publishers.request(target)
provider.publishers.requestWithProgress(target)
```

and you would use it like the following:
```swift
provider.publishers.request(target)
    .sink(receiveValue: { value in
        // ...
    })
```

## Option 3 - Use "combine" namespace (this is basically Option 2 with renamed namespace to "combine" instead of "publishers"

Usage:
```swift
provider.combine.request(target)
    .sink(receiveValue: { value in
        // ...
    })
```

I would like you to vote by using reactions to this post!
Option 1 - 👍
Option 2 - 😄
Option 3 - 🎉 

If you have other ideas - please comment below! Thanks.

**Comment by pedrovereza** [comment]
@sunshinejr Thanks for pushing this feature forward 🙏 ❤️ 

Leaving my 2 cents here in case others find it helpful:

I personally believe that, comparing the options in isolation, options 2 and 3 are _better_ designed and easier to read and use (that's my view on it, you're free to disagree). These would also be the best options because, as @sunshinejr mentioned, they follow the same pattern we already use for RxSwift and ReactiveSwift. However, I think it is important to consider the context in which these extensions exist.

We moved to using `.rx` and `.reactive` (in #1153) because they were/are _already_ used within the RxSwift and ReactiveSwift communities. We didn't create any new way of using it, we merely adhered to what was already there.

That's why even though I personally prefer options 2 and 3, I'm voting for option 1: to keep consistency with what already exists. This will hopefully make the usage of Combine on Moya more obvious and easier for people that are already using Combine or learning about it.

Examples from `Foundation`:

[`URLSesssion.dataTaskPublisher(for: URLRequest)`](https://developer.apple.com/documentation/foundation/urlsession/3329707-datataskpublisher)
[`URLSession.dataTaskPublisher(for:URL)`](https://developer.apple.com/documentation/foundation/urlsession/3329708-datataskpublisher)

**Comment by sunshinejr** [comment]
@pedrovereza yeah feeling the same. I don't like the `publisher` syntax at all, but I'm gonna create my own wrapper to wrap all these publisher into its own namespace in a separate project, no need to break the current design by Apple in Moya. Thanks everyone for participating!
