### ISSUE TITLE
Adding Moya as a dependency in Swift Package Manager causes the Previews in Xcode11 to crash.

### ISSUE THREAD

**Issue by uguizu** [Moya/Moya#1919]
**Moya version**: 13.0.1

I added the dependency in Swift Package Manager, and i see that the Package.swift for Moya includes in it's targets all the dependencies incluiding _ReactiveMoya_ and _RXMoya_.

The project builds and runs without any problem. But for some reason, loading the previews in Xcode does not work.

I also tried to change my project using Cocoapods instead of SPM, and using pods the previews actually worked.

The actual error message is the next one:

```
linker command failed with exit code 1 (use -v to see invocation)

----------------------------------------

Failed to build the scheme "theMovieUI": Link /Users/user/Library/Developer/Xcode/DerivedData/theMovieUI-fvtkhqlopskkqueykjpedojefpoa/Build/Intermediates.noindex/Previews/theMovieUI/Products/Debug-iphonesimulator/libCwlCatchException.dylib:
Undefined symbols for architecture x86_64:
  "_catchExceptionOfKind", referenced from:
      CwlCatchException.(catchReturnTypeConverter in _841BEC3F94220F0DFD4EA4E9DDB3DC93)<A where A: __C.NSException>(_: A.Type, block: () -> ()) -> A? in CwlCatchException.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)


Link /Users/user/Library/Developer/Xcode/DerivedData/theMovieUI-fvtkhqlopskkqueykjpedojefpoa/Build/Intermediates.noindex/Previews/theMovieUI/Products/Debug-iphonesimulator/libCwlPreconditionTesting.dylib:
clang: error: no such file or directory: '/Users/user/Library/Developer/Xcode/DerivedData/theMovieUI-fvtkhqlopskkqueykjpedojefpoa/Build/Intermediates.noindex/Previews/theMovieUI/Products/Debug-iphonesimulator/libCwlCatchException.dylib'
Command Ld failed with a nonzero exit code
```
I think the error comes from another dependency. But with the built-in SPM in XCode 11 i can't configure my dependencies to be excluded when compiling, because it does not generate a **Package.swift** file.

Maybe there's something I'm doing wrong? Or some configuration that I'm missing?

**Comment by sunshinejr** [comment]
Hey @uguizu, this is definitely not your fault. [This is the same problem we have noticed on SwiftyUserDefaults as well](https://github.com/sunshinejr/SwiftyUserDefaults/issues/211).

Basically because SPM fetches testing dependencies, even though they are not present in the main target, Xcode Preview sees them and tries to build it.  I will make PRs to fix both libraries ASAP. Sorry for the problem.

**Comment by uguizu** [comment]
@sunshinejr Sure, thanks the for the quick response and i gonna be waiting for the next update.

**Comment by sunshinejr** [comment]
@uguizu FYI I just released 14.0.0-beta.3 that should fix the issue.

**Comment by uguizu** [comment]
Thanks, testing the new version. now @sunshinejr

**Comment by barrypress** [comment]
I'm having this problem. Using Xcode 12 beta, Big Sur beta; Moya branch set to master in SPM. Perhaps I don't understand how to get the proper version?

**Comment by sunshinejr** [comment]
Hey @barrypress, so ideally you wouldn't use a branch but a version of Moya of your choice. This is because it's not advised from the code perspective, as things might break, but also because we have release scripts that hide certain dependencies that you don't need (and in this case it also broke Xcode Previews). 

[Here's](https://github.com/Moya/Moya/releases) a list of versions with changelog so you can take a look and see what fits you best. In case you have more questions, let me know!

**Comment by barrypress** [comment]
Thanks. I appreciate the reply.

I'm still confused, though. From the date stamps here <https://github.com/Moya/Moya/issues/1919>, I’d expected 14.0.0 to have fixed the problem. Nevertheless, my unit test builds (indeed, not previews) are failing in just this way. Is this perhaps a new problem, or do I just not understand what I need to be doing?

Thanks again

Barry

**Comment by sunshinejr** [comment]
@barrypress Hmm, I didn't notice any issues with unit tests that were caused by 14.0.0 - can you create a separate issue and give a little bit more details?

**Comment by barrypress** [comment]
I didn’t want to take up your time without good cause, so I dug into it further. That shows me a few things

This is a multiplatform app with the new build system, and the frameworks had to be added to the macOS target separately and using a different part of Xcode vs. how it’s done with iOS. I fixed that, but it didn’t help.  
I can build and run both iOS and macOS versions of the app having the unit test problem, and what functionality I’ve built so far works with Moya
I also verified that a new, empty app with just enough code to cause Moya to be linked would build for test cases just fine.

I’m not ignoring your request to open an issue, but don’t expect much from it if you can't repro the problem. To that end, I tried to build a cut-down app that demonstrates the problem, but after a day’s work I’m not there. I’d be happy to send the existing project to you, and if this is more of a packages issue than one of the code itself, then maybe stripping down to minimum code isn’t as important as it would otherwise be. 

So, how do you want me to put the issue together? Error captures only, or include the project?

Barry
