### ISSUE TITLE
JSON Dictionary attribute order is not consistent in body and then to create signature

### ISSUE THREAD

**Issue by jimijon** [Moya/Moya#1925]
Moya 11

I have to create a signature for my request based upon the JSON POST Body. However, when I convert the dictionary to a string the order of the attributes are different than when Moya parses the dictionary to make the json in the body.

1) Is there a way to just inject my jSON into the body as a string and not an object?
2) Otherwise how can I make sure my signing of the request uses the text json in the body?

Thanks

**Comment by sunshinejr** [comment]
@jimijon I think there are few ways to achieve this behavior:
- you can either use [`request(Data)`](https://github.com/Moya/Moya/blob/11.0.0/Sources/Moya/Task.swift#L10) task instead of passing a dict so you are sure you got the same ordering
- you can use a Plugin with `prepare` method implementation (similar to our [`AccessTokenPlugin`](https://github.com/Moya/Moya/blob/11.0.0/Sources/Moya/Plugins/AccessTokenPlugin.swift#L61-L77), just getting the body in there)

let me know if it helped!

**Comment by jimijon** [comment]
Yes I used variant 1 basically:

            return Task.requestData(body.data(using: .utf8)!)

where the var body was json converted to string then that string used everywhere. Thank you.

**Comment by sunshinejr** [comment]
Awesome, thanks for the update!
