### ISSUE TITLE
build failed in swiftui using moya with swift manager package 

### ISSUE THREAD

**Issue by mstudzitsky** [Moya/Moya#1947]
![Снимок экрана 2019-10-30 в 19 47 08](https://user-images.githubusercontent.com/15685681/67863507-3a8f4700-fb4e-11e9-8f28-a543e461137a.png)
Hi! I have a similar problem. I tried my 14 beta 3, 4, 5.
Xcode 11.1 macOs Catalina 10.15.1

_Originally posted by @mstudzitsky in https://github.com/Moya/Moya/issues/1941#issuecomment-547913610_

**Comment by sunshinejr** [comment]
@mstudzitsky hmm this seems quite different than #1941 as here there is a problem actually building Moya, not the testing frameworks...

There is an error about "undefined symbols" - this might actually be a problem with linking Moya - do you have it on your linked libraries list?

If so, can you actually build your "firstSwiftUI" schema? In that case please try clearing cache, closing Xcode, removing derived data and then opening the project again - does it help?

If it's still not working, please give us more info about your project (or even better if you could upload your project so that I can take a look). Info I would love to have would be package manager (with configuration), swift version, linked libraries/frameworks and the full error log/report you have.

**Comment by mstudzitsky** [comment]
Thanks a lot! Everything worked!  It was the linker. I don't understand why xocde doesn't do this automatically.

**Comment by sunshinejr** [comment]
@mstudzitsky awesome, glad it helped 🎉
