### ISSUE TITLE
Offline Disk Caching

### ISSUE THREAD

**Issue by ashfurrow** [Moya/Moya#197]
So, I spoke with @irace this week about a really neat idea for network requests in offline situations. If I understood correctly, each network request would do the following:
1. Serialize the request and store it on disk.
2. Try the request if you're online.
3. If it fails, or if the device becomes online and there are stored requests, resend them up to with max resend / max lifetime criteria.

It would be cool to do something like this with Moya. Maybe not in the primary repo, but maybe an extension or something in another repo. 

If anyone has ideas for feature requests, reference implementations, or ideas for how we could elegantly architect this, please comment!

**Comment by aschuch** [comment]
Sounds great!
I think we should also consider caching the result of any previous requests and replay them in case we are offline.

**Comment by ashfurrow** [comment]
Interesting idea!!

**Comment by irace** [comment]
@ashfurrow You have it correct. I can definitely share some more details on how this works in Tumblr.app (the code isn’t generic enough to be open sourced in it’s current form).

Let me know if you have any specific questions, additionally I can just dumb down our implementation and post some sample code or pseudocode.

**Comment by justinmakaila** [comment]
Could this potentially help with things like #164? If we provide an offline cache and specify a TTL at the request level, and whether or not a request should use the cache, I think we could ditch the idea of inflight requests.

**Comment by ashfurrow** [comment]
Yeah, I don't feel super-strongly either way about it. 

--
Ash Furrow
iOS Developer, Author
http://ashfurrow.com

**Comment by aschuch** [comment]
@irace Would you mind sharing some info/pseudocode of what you are using in Tumblr.app? Would love to get some more ideas. What kind of use cases do you cover with your implementation?

**Comment by jarrodrobins** [comment]
This is a great idea! I really like the idea of caching responses for use in offline situations (as suggested by @aschuch). I've implemented a similar thing in my own projects in the past. It's pretty straightforward and is super useful.

**Comment by ashfurrow** [comment]
Awesome, @jarrodrobins if you're able to share an existing implementation, we could discuss ideas for implementing the same here.

**Comment by jarrodrobins** [comment]
I don't think I can get away with sharing the existing code as the company I'm at isn't quite as open-source friendly as Artsy. ;-) But! That code's quite old, written well before Swift, sits on top of AFNetworking and isn't as generic as it could be. What I can do is explain what we did. 

This was purely for caching responses (not requests). 

The goal at the time was essentially to prevent users from seeing a loading indicator as much as possible. If they've loaded data before and there's a fair chance it hasn't changed, we should present existing data and update it in the background. This also handled the case of the user's internet dropping out. We only used it for `GET` requests (it doesn't really make much sense for POSTs, etc).

It doesn't make sense for some responses to be cached (eg, search responses). Others should be, but may be invalidated by a pull-to-refresh. So, we had an enum that we'd pass into our API client with each request that looked something like - 

    enum CachePolicy {
        case None, // don't cache the response
        case UpdateOnly, // don't show old data. eg, user just did a pull-to-refresh, but update the cache with what we get if we read it again
        case ReadAndUpdate // return old data and then go update it in the background. 
    }

I'm sure those names could be improved. For Moya, I can potentially see this as something that we could add to `MoyaTarget` as an instance variable. Obviously if the user's offline, there's no need to fire the update request.

How did we show old data/new data? If we had a cached response, we'd immediately call the response block (ie, `MoyaCompletion`), then go make the request anyway. If the data changed, the response block would be called again. So, that response block could therefore be called twice (I can see how that might be confusing, but since the developer would need to set a cache policy it wasn't too bad - by default it was disabled). 

Whenever we received a response, we'd wrap it in an object which contained a couple of other bits of metadata, namely -

- `data` - the NSData itself
- `ETag` - HTTP header for checking if the response actually changed or not. 
- `version` - This was an API version specific for our app. If we bumped our API version, we wouldn't use old cached responses at all. I'm not sure how we'd tackle this in Moya cleanly at this point. 

This object would then be saved to disk with the request URL as the key. 

Any time we would make a request, firstly we'd check the cache policy. 

- For `None`, simple - just fire off the request.
- For `UpdateOnly`, fire the request but save the response. 
- For `ReadAndUpdate`, check the cache and if an entry is found, return the response. Then for the interesting bit: we get ready to fire off the request anyway to update the data. We'd pull off that `ETag` field I mentioned earlier from the cached response and add it as a `If-None-Match` header for the request. Then fire the request. If that `ETag` hadn't changed, or if the response code was 304 (not modified), we wouldn't call the completion block. Otherwise, the updated data would be passed back up. 

I'm far from an expert on HTTP headers/ETags, but I understand that it's respected by `NSURLRequest` if you set the `cachePolicy` property to `NSURLRequestUseProtocolCachePolicy`. That's something AFNetworking seems to take care of itself (just looking at the header file documentation, I haven't looked into whether Alamofire does it).

We should probably also respect the `Expires` header (though that's something we didn't implement in our solution). 

I hope this all makes sense and that I haven't waffled on too much (I have a tendency for doing that). I'd definitely be keen to hear others' thoughts and suggestions on this and how it might be implemented. I'm more than happy to have a stab at it when I find some time if we agree on the method.

**Comment by irace** [comment]
At Tumblr, we have the concept of an `OutgoingRequest` and an `OutgoingRequestEngine`.

The request itself just models an HTTP request and conforms to `NSCoding`. It has:

* A type (certain types may have their progress reflected in the UI, others won’t)
* A URL
* A parameter dictionary
* (Optional) file names/paths/content types (for multipart file uploads)
* A created date (we won’t retry if a request is too old)
* A retry count (we’ll only retry so many times)

We keep all of these in an `OutgoingRequestStore`, which is some sugar on top of a thread-safe, persistent `NSArray` with some additional smarts like deleting files from disk once a request has finished (or we’ve given up on it).

The `OutgoingRequestEngine` is backed by an `OutgoingRequestStore` and requests are added to it from the application’s controllers/coordinators/whatever. It’s fairly naive at the moment but could be more sophisticated: it retries the requests in the store whenever `UIApplicationWillEnterForegroundNotification` is received, or whenever reachability changes. It does so in serial – requests are only processed one at a time in FIFO order. It has a delegate that can notify other parts oft he application about success/failure/progress.

**Comment by henkvanderspek** [comment]
Any progress on this or alternatives @ashfurrow?

**Comment by ashfurrow** [comment]
Afraid not that I'm aware of.

**Comment by scottrhoyt** [comment]
Looks like this was explored more recently in #713 and closed. Should we close this as well?

**Comment by PatrickSCLin** [comment]
any progress? this is what I looking for

**Comment by SD10** [comment]
@PatrickSCLin I'm afraid there's no progress on this. This could have some potential as a plugin but I'm not sure if it should be Moya's responsibility 🤔

**Comment by PatrickSCLin** [comment]
Do you know any sample codes about this that I can study? 

I'd like to make a plugin with moya, it will be useful in social app

從我的 iPhone 傳送
