### ISSUE TITLE
What would be the pattern for failure sampleData?

### ISSUE THREAD

**Issue by mhuusko5** [Moya/Moya#199]
Sometimes a signup endpoint succeeds and passes back no data, sometimes it fails and passes back data/info on what fields caused the failure. Not really sure how to model this in Moya.

Perhaps sampleResponse on endpoint, and sampleData on target should have failure specific cousins?

**Comment by ashfurrow** [comment]
The model is to return sampleData that reflects the info about the failure, just like on a success. We do this [here](https://github.com/artsy/eidolon/blob/5b724a68acd4e6e42d2e8b1092b4644ba6b6488b/KioskTests/Bid%20Fulfillment/RegistrationPasswordViewModelTests.swift#L14-L40) on a per-target basis.

**Comment by mhuusko5** [comment]
I'm a little lost. In that block of code I'm seeing neither the use of the `.Error` enum, nor for that matter (in the success cases) the user of `target.sampleData`..

I thought the target was supposed to define the data, with the endpointClosure mapping the sampleData to a sampleResponse?

**Comment by mhuusko5** [comment]
Having rethunk it, my real question is: if there's only one sampleData property, what am I do to if a target has sample data for success *and* sample data for failure? Other than that, I think I get the pattern for representing success/failure with endpointClosures.

**Comment by ashfurrow** [comment]
`sampleData` is actually a closure that returns an `NSData` instance. The demo I posted showed how you could customize the `endpointsClosure` to return customized `Endpoint`s. 

I suppose what's probably confusing is the `Success` and `Failure` cases of the result. `Failure` is truly a network failure – the status code is optional, even. It's meant to simulate when the device cannot connect to the internet. The `Success` case is a "success" in that the API returns some data. it's agnostic to the idea that a 404 would be a failure – it succeeded because it returned data. 

I've opened https://github.com/Moya/Moya/issues/200 to make sure that we clarify this for other users. 

Does that answer your question?

**Comment by colinta** [comment]
Your MoyaTarget implementation can have multiple `sampleData` properties, it is only a required `MoyaTarget` property so that it is easy to make use of `MoyaProvider.DefaultEndpointMapping`.

To use multiple sample data properties, you need to create your own endpoint-closure, which maps targets to `Endpoint<T>`:

```swift
    public static var endpointTestingClosure = { (target: YourAPI) -> Endpoint<YourAPI> in
        let method = target.method
        let parameters = target.parameters
        let sampleResponse = EndpointSampleResponse.Success(200, { target.testingData })
        // let sampleResponse = EndpointSampleResponse.Success(200, { target.sampleData })

        var endpoint = Endpoint<YourAPI>(URL: url(target), sampleResponse: sampleResponse, method: method, parameters: parameters, parameterEncoding: target.encoding)
        return endpoint.endpointByAddingHTTPHeaderFields(target.headers)
    }

    public static func TestingProvider() -> MoyaProvider<YourAPI> {
        return MoyaProvider(endpointClosure: testingClosure)
    }
```

**Comment by mhuusko5** [comment]
Your two answers combined covered the bases. I get it now. Thanks a bunch!

**Comment by ashfurrow** [comment]
I'm glad! I'm going to close the issue, but if you want to reopen later, or open a new issue, please feel free!
