### ISSUE TITLE
Alamofire Manager was removed from lib

### ISSUE THREAD

**Issue by MaximSkorynin** [Moya/Moya#1996]
Hi guys! How can I use this now?

<img width="949" alt="Снимок экрана 2020-02-19 в 23 29 31" src="https://user-images.githubusercontent.com/49302363/74863561-e8c63300-536f-11ea-99c1-728ba0ae2423.png">

**Comment by sunshinejr** [comment]
Hey @MaximSkorynin, this was due to the Alamofire change, they replaced `SessionManager` with `Session`. They probably have some migration guide, but you can check [how we provide a default `Session` in Moya here](https://github.com/Moya/Moya/blob/master/Sources/Moya/MoyaProvider+Defaults.swift#L28-L33). Let me know if it helps!

**Comment by failynsedik** [comment]
Same here. Can no longer use "ServerTrustPolicyManager" as well.

**Comment by sunshinejr** [comment]
hey @failynsedik, please see `Alamofire` [migration guide](https://github.com/Alamofire/Alamofire/blob/2b18f1e9c065e90f0adfe5aad8552ea5b0883f91/Documentation/Alamofire%205.0%20Migration%20Guide.md):
> `ServerTrustPolicyManager` has been renamed `ServerTrustManager` and now requires every evaluated request to match one of the provided hosts. This can be disabled by initializing an instance with `allHostsMustBeEvaluted: false`.

**Comment by MaximSkorynin** [comment]
> Hey @MaximSkorynin, this was due to the Alamofire change, they replaced `SessionManager` with `Session`. They probably have some migration guide, but you can check [how we provide a default `Session` in Moya here](https://github.com/Moya/Moya/blob/master/Sources/Moya/MoyaProvider+Defaults.swift#L28-L33). Let me know if it helps!

It works, thanks!
