### ISSUE TITLE
Support RxSwift 5.1.0

### ISSUE THREAD

**Issue by chiquan91** [Moya/Moya#2003]
Could you update your framework with Rx 5.1.0 dependency because of Apple's hard deprecation, starting April 2020: https://developer.apple.com/news/?id=12232019b

**Comment by sunshinejr** [comment]
@chiquan91 this should work out of the box, you just need to update the dependency graph to cover for new RxSwift release (we have ~> 5.0 constraint which should cover the 5.1 version as well). Did you try to see if it works?

**Comment by jdisho** [comment]
Ups, I got a bit confused. 
@sunshinejr I think you are right.

**Comment by chiquan91** [comment]
Thank you, i had run update and it had updated to RxSwift 5.1.0 as expected.

**Comment by MhmdRizk** [comment]
Hello everyone, 
I'm using RxMoya
I installed Moya using carthage, github "Moya/Moya" ~> 14.0
I tried uploading my app to the store anyway review team rejected the binary since it's still using UIWebView. I checked my code very well. 
then entered this comment in terminal in my project. and found out that even RxSwift 5.1.1 is using UIwebview 

`./Carthage/Checkouts/Moya/Carthage/Checkouts/RxSwift/RxCocoa/iOS/UIWebView+Rx.swift://  UIWebView+Rx.swift
./Carthage/Checkouts/Moya/Carthage/Checkouts/RxSwift/RxCocoa/iOS/UIWebView+Rx.swift:    extension Reactive where Base: UIWebView {`

did anyone face this issue? 
Thanks in advance.

**Comment by sunshinejr** [comment]
@MhmdRizk are you sure you're using RxSwift 5.1.1? did you check your Cartfile.resolved & Carthage build folder?

**Comment by MhmdRizk** [comment]
@sunshinejr , yup made sure.
`*** Checking out Moya at "14.0.0"
*** Checking out RxSwift at "5.1.1"
*** Checking out ReactiveSwift at "6.2.1"`
I'm using RxGesture, but I made sure they updated and using latest. 
`*** Checking out RxGesture at "3.0.3"`

**Comment by sunshinejr** [comment]
@MhmdRizk please double check the Carthage build folder, the files you mentioned are not there on the RxSwift 5.1.1 version: https://github.com/ReactiveX/RxSwift/tree/5.1.1/RxCocoa/iOS

**Comment by MhmdRizk** [comment]
@sunshinejr  I removed the project and downloaded it again. and then after updating carthage again everything worked. 
Thank you
