### ISSUE TITLE
How to access the state of Alamofire.Request

### ISSUE THREAD

**Issue by tarun-personatech** [Moya/Moya#2006]
How do I check the state of the actual request that was made? I need to know whether the request is still in progress without hooking into the completion handler.
`Alamofire.Request` exposes a `state` property for this. But Moya wraps this Request into a `Cancellable` protocol that just exposes `isCancelled` nothing else related to the state.

**Moya Version 14.0.0
Not using RxMoya or ReactiveMoya
Alamofire Version 5.0.2**

**Comment by sunshinejr** [comment]
Hey @tarun-personatech - I think it's not currently possible due to wrapping in our cancellable type. There are plans to extend this to support more than just the cancelling part though (like resuming, and possibly other functionalities). For now I guess you would have to work around this by setting the state yourself if possible (depending on your architecture, if you have an abstraction layer on top of `MoyaProvider`, you could store array of cancellables and update it once the request starts/stops so you know if it is in progress or not)

**Comment by tarun-personatech** [comment]
Thanks @sunshinejr , I kind of knew the answer and realized it won't be possible without adding to Cancellable type or at the least without exposing the alamofire request in `CancellableToken`.
I will find some workaround. Thanks again.

**Comment by tarun-personatech** [comment]
One question though. I am not at all familier with RxSwift but planning to start using it. Would this thing be possible if I use RxMoya which I guess returns a Signal?

**Comment by sunshinejr** [comment]
@tarun-personatech hmm I don't think so, no, since `Single` does only provide an abstraction over the `Response` you will normally get from Moya. Meaning, you will get a form of "stream of Responses" instead of just `Response` (`Observable<Response>`) or just a specialized stream of values, that is in fact only one value (success/failure, `Single<Response>`). It still uses a `Cancellable` under the hood for the request logic.
