### ISSUE TITLE
HTTPS requests wait for each other, HTTP is good

### ISSUE THREAD

**Issue by kobeli** [Moya/Moya#2031]
I found that if I request two HTTPS APIs A and B at the same time, their response time is the same, which means that if A is not completed, B will wait. So I use Alamofire to make requests separately, there is no such situation. Can you help me?
<img width="842" alt="WX20200422-093009@2x" src="https://user-images.githubusercontent.com/3961585/79930770-ea010280-847b-11ea-904c-3ce4d72301b5.png">

**Comment by sunshinejr** [comment]
Hey @kobeli, sorry for late response - I was looking at this issue the other day but I couldn't figure out what could be the issue.

First, it's really strange that it happens only to HTTPS requests and also works correctly on Alamofire - are you sure this is the case? If it wasn't bound to HTTPS only, we could suspect that maybe there is a lock bug somewhere in the codebase, but the HTTPS-only requirement kinda puts me off track.

Are you able to consistently reproduce it? If so, maybe you could try to recreate a small example app that I could investigate further?

**Comment by kobeli** [comment]
@sunshinejr Sorry, I'm late. I definitely this issue. I will let my backend colleague make  API that you can test and send to you tomorrow.  Thank you.

**Comment by sunshinejr** [comment]
@kobeli that would be awesome, thank you!

**Comment by kobeli** [comment]
@sunshinejr  I recreated a small example app with Moya. That looks well.  very strange. I used Moya + RXSwift + ObjectMapper.

**Comment by sunshinejr** [comment]
@kobeli sorry, didn't see that you updated the message. Thank you for the investigation! I was wondering, do you think it could be a problem on the backend side? I'm wondering what could be the issue here, but the latency parameter equals the duration one in the Charles session, so there might be a chance that server performs some work before returning the response.

Also, one other thing we could test is whether on URLSession / Alamofire itself it happens as well.

**Comment by sunshinejr** [comment]
@kobeli friendly bump!

**Comment by kobeli** [comment]
@sunshinejr Thanks for help. URLSession / Alamofire happened. 😭
