### ISSUE TITLE
Example projects - `carthage update` command stuck

### ISSUE THREAD

**Issue by therohansanap** [Moya/Moya#2036]
I want to tryout Example project and for that I downloaded .zip of repository and inside repository folder, I run `carthage update` command as described in docs. But this process is stuck at following step and doesn't move ahead:
<img width="1297" alt="Screen Shot 2020-04-30 at 4 39 36 PM" src="https://user-images.githubusercontent.com/11019636/80704066-8b81f700-8b01-11ea-9641-a69e101b7833.png">

**Comment by therohansanap** [comment]
Stuck process continued and completed with following message:
<img width="1680" alt="Screen Shot 2020-04-30 at 4 44 49 PM" src="https://user-images.githubusercontent.com/11019636/80780944-4fe13e80-8b8e-11ea-9e0a-eaf99678bc01.png">

**Comment by amaurydavid** [comment]
You are using a swift compiler that is not compatible with the fetched RxSwift binary. You may want to either use an older compiler with the `xcode-select` command. 
[More info here](https://github.com/Carthage/Carthage#resolve-build-failures)

**Comment by sunshinejr** [comment]
@therohansanap with Carthage there is a possibility to upload a pre-compiled binary to the GitHub releases. This speeds up the `carthage` process since it won't need to compile it itself. But, because of multiple limitations, we can only provide the pre-compiled binary once per a release - thus, it is compiled with specific Swift version. And because of module stability, RxSwift needs rebuilding with each new Swift version. And so, they pre-compiled the binary with Swift 5.2 and you are using 5.2.2, which means Carthage cannot use the binary and needs to compile it itself. It's not really an error but an info for you.

As @amaurydavid noticed, you can use older compiler if you want to use the pre-compiled binary.

Another info would be to use `carthage bootstrap` instead of `carthage update` so it doesn't have to resolve the dependency tree and just use what's there. And if you want even faster builds in the future `--cache-builds` flag would be a life-saver for you. Also if you care only about one platform, you could add `--platform` flag. With all that, when you run:
```bash
carthage bootstrap --platform iOS --cache-builds
```
you will notice pretty big improvement to your day-to-day work.
