### ISSUE TITLE
Compatibility between Moya/RxSwift and RxSwift 5

### ISSUE THREAD

**Issue by MiltonPacheco89** [Moya/Moya#2038]
Hello.

Today i'm facing the challenge of removing the references to UIWebView within my app, in order to successfully do that, i need to update the RxSwift version to 5.1.0, but i'm getting the following error from cocoa pods:

Moya/RxSwift was resolved to 13.0.1, which depends on
      RxSwift (~> 4.0)

updating Moya to version 14 also means to update Alamofire and PromiseKit, is there a way to use RxSwift 5.1.0 with Moya 13 and also use Moya/RxSwift?

Sorry for the redaction, English is not my native language.

Thank you.

**Comment by jdisho** [comment]
Hey @MiltonPacheco89, not sure if this is achievable. However, there is a [workaround](https://github.com/Moya/Moya/issues/2019#issuecomment-605949970) I've applied in one of my projects.

**Comment by sunshinejr** [comment]
Yeah sorry about that @MiltonPacheco89! I was thinking if we could create a patch/minor version update to Moya 13, but it doesn't seem very appealing. Because Moya 13 uses RxSwift 4, upgrading it to version 5 in a patch/minor version could introduce breaking changes to people that rely on RxSwift 4.

For the time being it seems like what @jdisho suggests is a pretty good alternative: use the core of Moya and copy the files for RxSwift extensions. Alternatively, you could create a fork in which you would just bump the RxSwift version to Moya 13.

**Comment by MiltonPacheco89** [comment]
thank you, I managed to solve the issue implementing @jdisho idea.
