### ISSUE TITLE
how can I close the https certificate validation?

### ISSUE THREAD

**Issue by XinjianQi** [Moya/Moya#2041]
When my app is launched by me, the https requests will take a long time. I think the requsts are need https certificate validation. So I want to know how to close the https certificate validation in moya. Thanks.

**Comment by XinjianQi** [comment]
help!

**Comment by sunshinejr** [comment]
Hey @XinjianQi, sorry for the late reply. So usually you don't really want to disable trust validation for the server certificate due to security reasons, but there is `ServerTrustManager` that you can pass to the `Session` in `MoyaProvider` initializer:
```swift
let manager = ServerTrustManager(evaluators: ["yourserver.com": DisabledTrustEvaluator()])
let session = Session(serverTrustManager: manager)
let provider = MoyaProvider<MultiTarget>(session: session)
```

though I would check if the server your using is not having issues with the https entries. You can try with postman e.g. to see if there is a difference and to figure out if it's a client or server issue. You can also post a request code here and maybe there is something we can do from client side as well.
