### ISSUE TITLE
After updating to the latest version, there will be a problem with the introduction of result

### ISSUE THREAD

**Issue by Jacket12** [Moya/Moya#2058]
After updating to the latest version, there will be a problem with the introduction of result. The previous introduction will prompt no such module 'result'. How to solve this problem. Need to sign out

**Comment by sunshinejr** [comment]
@Jacket12 yes we don't use the `Result` type anymore in `Moya`. Though I'm not sure where is the error coming from - is this a console log/build/runtime error? Please provide a little bit more details so we can help!

**Comment by Jacket12** [comment]
![image](https://user-images.githubusercontent.com/16936767/84969543-81689600-b14b-11ea-8e4e-0a50a0be5276.png)

@sunshinejr  Hello, this is a post run error. There is no problem with the previous version, but this error will be prompted after updating to the latest version. My Xcode version is 11.4.1. I used pod 'Moya / rxswift', '~ > 14.0' to enter. Shall I introduce it?

**Comment by sunshinejr** [comment]
@Jacket12 so since that version there is no need to import `Result` - we do not provide that dependency anymore and we use the `Result` type that Swift introduced instead. So removing the import should fix the issue, unless you are using an older version of Swift that doesn't have the `Result` type, in that case you would need to stay on the previous Moya version until you can update your Swift version.

**Comment by Jacket12** [comment]
OK，Thank you！
