### ISSUE TITLE
Gitter Integration

### ISSUE THREAD

**Issue by justinmakaila** [Moya/Moya#206]
@Moya/contributors 

All,
Is there any interest in setting up a gitter.im room for the organization? I find that I have some questions regarding the future of Moya and the direction we want to go, but am reluctant to file an issue, because it's not necessarily related to the code (Just like this one!).

**Edit**: I'm happy to take care of the integration.

**Comment by ashfurrow** [comment]
Meta-issue :)

I've not used gitter, and I don't really feel like inviting people to another Slack just for Moya :sweat_smile: I personally like issues because they're public, searchable, and anyone can easily participate. Even for things like roadmaps, I feel it makes sense. But I know my feelings aren't universal, too. Happy to go in whatever direction we need to to make a great library.

**Comment by colinta** [comment]
I agree, especially because of "searchability".

I have bad luck with chat-room-as-support-channel.  In chat rooms, people seem to assume that the people there have tons of free time available, to _answer their question right now_, even though a quick search would yield the answer they need, or opening an issue would help people out in the future.

**Comment by colinta** [comment]
On the other hand, if there are maintainers who DO want to hang out in that chat room, it wouldn't hurt to have it!  But an empty gitter room, with a link from the README, might give people the wrong idea.

**Comment by esttorhe** [comment]
I've never used `Gitter` before TBH.

Would give it a try as long as someone could point me to the benefits of having a Gitter room vs only the issues here.

I think @colinta and @ashfurrow already made some valid points of pros for the issues in Github but I still don't know what are the benefits of the other option.

**Comment by steam** [comment]
I'll throw my vote in for using GH issues. One of the problems with a separate discussion tool in my opinion is fragmenting the conversation and not preserving it for the future. Future Moya users (and current ones) can easily search and read the conversation history in GH.

**Comment by orta** [comment]
Gitter's tend to end up like Alcatraz's : https://gitter.im/supermarin/Alcatraz - people come in with  questions but no-one gives answers.

Not to say that a slack doesn't have it's problem, or IRC; on CocoaPods we devs don't use the IRC so it's only usually for people who can help each other.

**Comment by esttorhe** [comment]
I think the «vast» majority is against `Gitter`.

I agree that the fragmentation would be an issue.
How does `Gitter` work in regards of; I don't know. Google indexing? Would I get hits in Google pointing to `Gitter`? how long does the discussions in `Gitter` are stored? or are they discarded after X amount of bytes?

I think having an outlet for users to help themselves would be great; but if as long as there's not a way to preserve and index said discussions they would go to «waste»

**Comment by ashfurrow** [comment]
Gonna close this – if we missed something in the discussion, or if it makes sense in the future, we'll revisit some sort of organizational chat :+1: :cake:
