### ISSUE TITLE
Memory leaked, When we request API.

### ISSUE THREAD

**Issue by TSritrakul** [Moya/Moya#2070]
Xcode 12 (Beta)
iOS 13.5.1
- Alamofire (5.2.1)
  - Moya/Core (14.0.0):
    - Alamofire (~> 5.0)
  - Moya/RxSwift (14.0.0):
    - Moya/Core
    - RxSwift (~> 5.0)
  - RxSwift (5.1.1)

This is code in my project.

```
public func getDscShelfData() {
    let provider = MoyaProvider<DSCShelfCDNProvider>()
    provider.request(.getBaseShelf) { (response) in
    }
}
```

```
import Moya
import Core

public enum DSCShelfCDNProvider {
    case getBaseShelf
}
// MARK: - TargetType
extension DSCShelfCDNProvider: TargetType {
    
    public var baseURL: URL {
        return URL(string: "https://discover.dmpcdn.com/discover/")!
    }
    
    public var path: String {
        var node = "tid_discover_page/"
        switch self {
        case .getBaseShelf:
            node.append("base_shelf")
        }
        return "\(node).json"
    }
    
    public var method: Moya.Method { return .get }
    
    public var sampleData: Data { return Data() }
    
    public var task: Task {
        return .requestPlain
    }
    
    public var headers: [String : String]? {
        return nil
    }
}
```

We check leak with instruments tool and we found leak about calling api from Moya.

<img width="1680" alt="Screen Shot 2563-07-14 at 15 46 58" src="https://user-images.githubusercontent.com/52536209/87405198-4aba5a00-c5e9-11ea-92cf-9bb5b5903258.png">

**Comment by sunshinejr** [comment]
@TSritrakul can you provide a little bit more details how you call the request? With the function you specified you shouldn't be able to even get the response since you're not retaining the provider, so I guess you use it a bit differently. Would help if you did also demonstrate how do you use the response. 

Ah, also I don't see anything related to Moya in the leaks screenshot you provided - is this a correct one? Are these addresses Moya calls? Ideally I'd love to see symbolicated stack 😄

**Comment by TSritrakul** [comment]
Oh. The leak is disappeared. It's my fault. Sorry :)

**Comment by sunshinejr** [comment]
@TSritrakul no issue at all - hope the fix was easy!
