### ISSUE TITLE
Invalid Manifest failed to load package.

### ISSUE THREAD

**Issue by mahabaleshwarhnr** [Moya/Moya#2273]
I have added Moya to my sample swift package.  Looks like Moya swift package manifest have some error..

```
dependencies: [
        // Dependencies declare other packages that this package depends on.
        .package(url: "https://github.com/Moya/Moya.git", .upToNextMajor(from: "15.0.1"))
    ],
```

Version: Version: 15.0.1

**Error Screenshot**: 

<img width="559" alt="Screenshot 2022-08-12 at 4 23 47 PM" src="https://user-images.githubusercontent.com/11162668/184340528-d16e014b-f1ec-4441-88f2-bb9d7ef37569.png">

**Comment by mahabaleshwarhnr** [comment]
@BasThomas can you please help here. Our few projects are not compiling now.

**Comment by lukewakeford** [comment]
I'm seeing the same error because I'm using [Japx](https://github.com/infinum/Japx/blob/master/Package.swift) that depends on this library.

I've not found a solution but I'm going to try including moya at a lower package version

`.exact(“15.0.0”)`

---

Having a quick look at `15.0.1` it's possible [the changes to Package.swift ](https://github.com/Moya/Moya/blame/15.0.1/Package.swift) are to blame for this breakage - the `name` param being commented out on line 68 specifically.

**Comment by TTOzzi** [comment]
It can be fixed temporarily like this.
`.package(url: "https://github.com/Moya/Moya.git", revision: "28457ca112bf645960c8b44796adce7dbc297ab0")`

**Comment by AndrewSB** [comment]
sorry about that, that seemed to have been an automated change by our release tool, Rocket. i'll take a look and fix it now

**Comment by AndrewSB** [comment]
testing a fix here https://github.com/Moya/Moya/pull/2275

**Comment by AndrewSB** [comment]
apologies for the breakage! thanks for isolating the problem @lukewakeford. could you test the latest release, https://github.com/Moya/Moya/releases/tag/15.0.3 and let me know if that parses in your project?

**Comment by lukewakeford** [comment]
No prob, thanks for the hotfix! I'm running a build now.

**Comment by lukewakeford** [comment]
Yep my pipeline is all green here ✅ - many thanks 👍🏻

**Comment by AndrewSB** [comment]
big apologies for the breakage. thanks for reporting and testing. i'll close this out!

**Comment by mahabaleshwarhnr** [comment]
Thanks  folks for the quick fix
