### ISSUE TITLE
Cut version 5 and 🚢

### ISSUE THREAD

**Issue by swizzlr** [Moya/Moya#300]
I've created a v5 milestone. We shouldn't let breaking changes fester in master too long before releasing a release candidate, but while we're at it let's sneak some more stuff in!

I've identified five issues that I think should be resolved for v5; take it up in those issues if you think they should be descoped.

With this issue I'm opening the floor to any other suggestions for issues to be added to the v5 milestone.

Let's draw a line under planning any more features to v5 by, say, **Wednesday 18th November** (that is to say, a freeze on deciding what will go into v5, not doing it obviously), if only to stop it from bloating too much.

**Comment by ashfurrow** [comment]
Yeah, I like the idea of a milestone but I'm not sure we need any specific date to plan on. We can evaluate issues for version 5 on a case-by-case basis, and if anyone feels we're waiting too long, we can talk about it. 

This is also a great issue to discuss anything that's missing (changelog entries, for example). Thanks T-Swizzle.

**Comment by ashfurrow** [comment]
So I think we're in a good spot now to release _a_ build. I know we still have 5.0.0 issues open, but many of them are either longer-term or could be done without breaking changes. It's been a while since we made a release and I don't want us to get to _too_ far away from the existing release. Does anyone have anything they want to make sure gets in this release? /cc @Moya/contributors

**Comment by petester42** [comment]
I think some protocols could be still be renamed to match the new ones that remove the Moya from their name

`MoyaTarget` -> `Target`
`MoyaResquest` -> `Request`

Maybe change the naming of some protocols to include `Type` or `able` at the end like a lot of swift protocols do. Would clearly show the line of separation between what is and isn't a protocol. Right now something like `MoyaTarget` might be confusing since it is not actually a target but a protocol that targets need to implement. `TargetType` might make more sense for users.

**Comment by petester42** [comment]
Also if `Endpoint` is never supposed to be subclassed we could mark it as `final`. Anyone have a use case where `Endpoint` would need to be subclassed?

**Comment by ashfurrow** [comment]
_Yes_. These all sound amazing. 

`Endpoint` should never be subclasses, so making it `final` is :100: I'll try and get to these changes this weekend.

**Comment by ashfurrow** [comment]
OK, anything else? I'll cut a release tomorrow morning if that's all.

**Comment by ashfurrow** [comment]
Cool cool, this is released in https://github.com/Moya/Moya/commit/117af026df08d006aaac317c92294ebb9d5dffd1 with the podspec at https://raw.githubusercontent.com/CocoaPods/Specs/e0bf8b03d24b0b23829d8667298591ef5a431dfd/Specs/Moya/5.0.0/Moya.podspec.json .

So I'll close the issue and migrate the 5.0.0 milestone to a the "longterm" one.
