### ISSUE TITLE
Is that possible to intercept a request before sending it using plugin?

### ISSUE THREAD

**Issue by mrahmiao** [Moya/Moya#326]
I conformed PluginType to intercept the request, the `NetworkLoggerPlugin` do logged the changes I've made. However, I can see nothing changed in outgoing requests through Charles app.

Here is my code:

```swift
// Plugin
struct InterceptPlugin: PluginType {
  func willSendRequest(request: RequestType, target: TargetType) {
    (request.request as? NSMutableURLRequest)?.allHTTPHeaderFields = ["Hello": "World"]
    (request.request as? NSMutableURLRequest)?.HTTPBody = "RxMoya".dataUsingEncoding(NSUTF8StringEncoding)
  }
  
  func didReceiveResponse(result: Result<Response, Error>, target: TargetType) {
    
  }
}

// Provider

lazy var provider: RxMoyaProvider<HTTPBin> = {
    return RxMoyaProvider<HTTPBin>(plugins: [InterceptPlugin(), NetworkLoggerPlugin()])
}()

```

**Comment by wangshengjia** [comment]
You sure about ```(request.request as? NSMutableURLRequest)?``` will not give a ```nil``` cause ```NSURLRequest``` not same as ```NSMutableURLRequest``` ?

**Comment by mrahmiao** [comment]
I've printed the request and the mutable request do exist. 

```swift
print(request.request)           // Optional(<NSMutableURLRequest: 0x7fa0fbf12e30> { URL: http://httpbin.org/post })
print(request.request != nil)    // true
```

This is what the logger logged:

```
["Moya_Logger: [02/12/2015 05:53:18] Request: <NSMutableURLRequest: 0x7fd5134ae1c0> { URL: http://httpbin.org/post }", "Moya_Logger: [02/12/2015 05:53:19] Request Headers: [\"Content-Type\": \"application/x-www-form-urlencoded; charset=utf-8\", \"Hello\": \"World\"]", "Moya_Logger: [02/12/2015 05:53:19] HTTP Request Method: POST"]
```

**Comment by wangshengjia** [comment]
Hmm.. you are right.

Apparently, it's because ```willSendRequest``` get called after ```request.resume()```... (It should not !)

So the workaround for now is using the approach mentioned by @ashfurrow in issue #325, it will work.

**Comment by mrahmiao** [comment]
Yes, the workaround in issue #325  can be used to solve my interception problem.

And I think the solution of the plugin interception is to pause the request in the initializer of `MoyaProvider` by setting property `startRequestsImmediately` of the Alamofire manager to `false`. And then resume the request after enumerating plugins in `sendRequest(_:request:completion:)` of `MoyaProvider`.

**Comment by ashfurrow** [comment]
Sounds like something that the library should fix :smile: Could someone open an issue (or send a pull request :wink:)?

**Comment by wangshengjia** [comment]
I've finally got some time in weekend and could be back to this issue. Here is my rethought.

- All the manipulations of ```NSURLRequest``` should be done in either ```endpoingClosure``` or ```requestClosure```, the latter is the original way to **resolve/alter** a request, and should probably be the answer of this issue. (I should've noticed it at the first place:disappointed: ).
- It is probably not a good idea to manipulate `request` in `plugin`. 
Think about this case: assume we have ```let plugins = [A, B, C, D]```, 
 - `C` could sometimes break `A`, because `C` could alter some value which already have been altered by `A` again accidentally, then we got a silent failure.
 - `D` will be functional based on `B`, which means `[A, B, C, D]` will work, but [A, D, C, B] will not work.
 - :bomb: 

  The `Plugin` mechanism is basically a "multicast delegation" pattern. If we do not keep every ```plugin``` entirely independent (such as alter the same instance one by one), we could easily entry into a mess.

**Conclusion:**
- This is not a bug. :wink: 
- We may need to rethink also the implementation of `CredentialsPlugin`. :thought_balloon:

**Comment by mrahmiao** [comment]
Never notice the `requestClosure` ever before. Let me have a try on it.

**Comment by mpurland** [comment]
I agree with @wangshengjia about the ```Plugin``` mechanism for manipulating requests can have problems. We could solve this with some type of requirements, ordering, priority, or another type of streaming/proxy solution (something along the lines of https://github.com/typelift/Aquifer comes to mind).

**Comment by ashfurrow** [comment]
Using `requestClosure`, is this issue is resolved?

**Comment by mrahmiao** [comment]
@ashfurrow Resolved.
