### ISSUE TITLE
Moya's Response type is ambiguous from outside the module

### ISSUE THREAD

**Issue by tomburns** [Moya/Moya#368]
I hit an issue (#367) when attempting to use Moya's `Response` type in my code. When used from outside the module, it's easy to end up in ambiguous states where the compiler can't tell if you want Alamofire's `Response` or ours.

Since Alamofire is a dependency, should we consider prefixing or renaming `Response` to avoid this potential confusion? The fix is admittedly simple once you realize what's going on (referring to the type as e.g. `Moya.Response`), but may not be obvious to people who haven't encountered it before.

**Comment by tomburns** [comment]
I'm not sure I have a strong opinion either way, just wanted to open the table for discussion.

**Comment by ashfurrow** [comment]
Definitely, thanks for opening the issue @tomburns. 

This question is bigger than just Moya and something the entire Swift OSS community will need to answer. I don't have strong opinions, either. Maybe this is the new norm and we just need time to get used to it. Of course, lots of people said the same thing when _The Phantom Menace_ was released and look how that turned out.

Does the compiler error present when only importing `Moya`'s module, or when you link with Alamofire at all?

In any event, documentation and sample code should be updated to reflect the fact that using Moya's `Response` type requires namespacing it with `Moya.Response`.

/cc @Moya/contributors

**Comment by justinmakaila** [comment]
I think `Moya.Response` and `Alamofire.Response` are the most responsible ways to access the types. I don't think we should be forced to prefix our types due to external collisions, especially when the solution is as simple as saying `Module.SomeType`

**Comment by gregpardo** [comment]
This has been discussed previously. I think what is currently implemented is the standard swift way. You can always alias if you want to use something else right?

**Comment by tomburns** [comment]
@gregpardo Certainly, and perhaps the real issue here is that the Xcode error when you encounter this sort of ambiguity doesn't volunteer the more specific types as a FIXME. As I said, I wasn't sure any action was necessary here, but figured it couldn't hurt to make sure we had consensus either way :)

Thanks for the discussion!

**Comment by sunshinejr** [comment]
I think we can close this one, but if there is something to add to the discussion, please let us know! 🐼
