### ISSUE TITLE
JSON-based Logging Plugin

### ISSUE THREAD

**Issue by ashfurrow** [Moya/Moya#392]
We currently have a barebones network request/response logging plugin: https://github.com/Moya/Moya/blob/bd4f36bd958eaadd01d5266db61b8705d5e02447/Source/Plugins/NetworkLoggerPlugin.swift But it just dumped out the data (converted to `NSString` to the console). It'd be cool to have something that tries to convert it to JSON instead, so it's more readable. Maybe a new plugin, maybe an option to the existing one. 

See conversation at https://github.com/Moya/Moya/issues/391 for details and motivation.

**Comment by wattson12** [comment]
I'd be happy to help on this one. I took a quick look and first thoughts are to add an optional response data formatter function to the logger (called only in verbose mode). This way a user can format data however they want, maybe with the demo updated to include a formatter closure 

In testing I was using a quick and dirty data -> NSJSONSerialiazation object -> NSJSONSerialiazation  pretty printed data function

The other problem is that even formatted strings are printed without formatting when printing as part of the array, so the output function will need to print item by item rather that array as a whole (probably only in verbose mode since it increases the console real estate used)

I can open up a pull request if that sounds good

**Comment by ashfurrow** [comment]
A pull request would be awesome! I'm not sure I quite understand this:

> even formatted strings are printed without formatting when printing as part of the array

But I trust you'll come up with a good solution :+1:

**Comment by wattson12** [comment]
Cool, will put something up later today.

To give an example this is some simple JSON as a string returned by NSJSONSerialiazation with .PrettyPrinted as an option:
```
{
  "id" : 1,
  "name" : "first object"
}
```

And this is the same object when printed inside an array (i.e. the way response components are printed in NetworkResponseLogger):
```
["{\n  \"id\" : 1,\n  \"name\" : \"first object\"\n}"]
```

**Comment by ashfurrow** [comment]
Huh! I'd have thought it would deal with that :disappointed: Oh well, thanks again!

**Comment by orta** [comment]
That might be the core part of the issue, perhaps it has to escape the array in order to be printed?

**Comment by wattson12** [comment]
I tried printing the `logNetworkResponse` array item by item, and overall its an improvement (it breaks up headers and becomes a lot more readable), but the response JSON component is still unformatted (or i guess more accurately it matches the formatting returned from the server)

**Comment by ashfurrow** [comment]
Fixed in https://github.com/Moya/Moya/pull/394
