### ISSUE TITLE
Documentation for plugin use / customisation 

### ISSUE THREAD

**Issue by wattson12** [Moya/Moya#397]
There is some background / discussion in #394 

As part of adding JSON formatting to the network logger plugin I added an optional formatter closure. This works fairly well but a user wanting to customise something else, e.g. print only some headers would need to make a change to the code

So this ticket probably represents 2 questions:
- Can we add some more documentation for the existing plugin setup
- Should we change the network logger to something more easily extensible (e.g. a network logger plugin, with a JSON network logger plugin as subclass in the demo)

**Comment by sunshinejr** [comment]
Because we are currently in the middle of changing the documentation and examples, it would be _awesome_ to add some documentation on plugins as well. What comes to my mind would be a new file, let's say `Plugins.md`, which will cover the basics, and also we could add examples to our new [examples directory](doc/Examples). What do you think about it @wattson12? Also would you be up for the PR as well? 🐼

**Comment by wattson12** [comment]
Sounds good, I can take a look

the examples directory link in your comment is 404 for me though?

**Comment by ealeksandrov** [comment]
Valid link will be https://github.com/Moya/Moya/tree/master/docs/Examples

**Comment by sunshinejr** [comment]
Whoops, my bad! @ealeksandrov got the right one, I've also edited mine.

**Comment by sunshinejr** [comment]
This one was implemented in #514, closing.
