### ISSUE TITLE
Question about Provider

### ISSUE THREAD

**Issue by remirobert** [Moya/Moya#413]
Hi, I have few questions :grey_question: about the Provider.

- Is it only **1 Provider** per endpoint, and then per request ?
- If I have several request to do in my controller, **do I need several Provider** ? 

🤔:thought_balloon:

**Comment by colinta** [comment]
Simple answer: you pretty much just need two providers *per app*. One to send actual requests, and one for stubbing (during tests). 

Using a "shared provider" (a global) makes sense, so that you can set it to the "actual" or "stubbing" instance as needed. 

You might create additional providers to provide more stub providers (delayed, immediate, errors), but I can't think of a reason to have more than one "real" provider. Anyone else?

**Comment by remirobert** [comment]
@colinta Thanks for your answer, makes sens.
But how can I execute several request with only 1 provider ?

**Comment by remirobert** [comment]
I was also wondering, if I have to change my header, depending of the request, do I have to recreate the Provider ?

**Comment by wattson12** [comment]
@colinta I use multiple providers because I have multiple endpoints I am calling (e.g. an auth service and a content service) so I like to have different named providers for readability (I also use different TargetType enums for each to stop them getting too complex)

**Comment by wattson12** [comment]
@remirobert you should be able to send as many requests on the same provider as you like. The bottleneck here (apart from the quality of the connection, type of request being made etc) is the underlying `NSURLSessionConfiguration`. It has a default value of 4 for `HTTPMaximumConnectionsPerHost` but you could initialise a provider with a custom configuration if you wanted to change that

**Comment by sunshinejr** [comment]
Does that answer your questions @remirobert? 🐼
