### ISSUE TITLE
Path parameters

### ISSUE THREAD

**Issue by onemanstartup** [Moya/Moya#417]
I found how this working by debugging. There is no information in docs.
When I pass one parameter like id it just works
```swift
    case DELETEApiActivitiesIdJson(let id):
      return "/api/activities/\(id)"
```
But when I pass multiple parameters it behaves like object
```swift
    case PATCHApiActivitiesIdJson(let activity):
      return "/api/activities/\(activity.id)/"
```
A little bit confusing don't you think? Thanks.

**Comment by sunshinejr** [comment]
Hey!

It is because you are assigning tuple of parameters to the activity constant. It is now a tuple and when you have your variables named then you can access it like you have shown `activity.id` etc. If you didn't have them named, access to it would be like `activity.0`, `activity.1` etc. If you want to assign your parameters not to a tuple, but to a variables, just specify them in the parenthesis, like:
```
case PATCHApiActivitiesIdJson(let id, let nextParam, let nextNextParam):
      return "/api/activities/\(id)/"
```

Hope it is now clear :beers:

**Comment by onemanstartup** [comment]
@sunshinejr thanks for quick reply. Yeah it helps. The problem though, is why id is not a tuple? I guess it is a language feature, I need to learn a bit more swift :)

**Comment by sunshinejr** [comment]
@onemanstartup If you specify _only_ one parameter (when you need to assign more than one) in enum's case, it will convert it to a tuple of parameters, otherwise it won't. So in your case, if you have e.g. 3 associated types, when you specify one, all parameters are converted into a tuple (because you need to catch all the values), and then passed to the variable. If you specify all parameters, it doesn't convert it to the tuple, that's why `id` in my case isn't a tuple, because we have all parameters already. 

Don't worry, swift is evolving all the time, no-one knows everything about it, learning is a key. Keep it up :)  🎉

**Comment by onemanstartup** [comment]
@sunshinejr got it, thank you very much for explanation!
