### ISSUE TITLE
Must stubbed responses be included in the main target?

### ISSUE THREAD

**Issue by hirad** [Moya/Moya#425]
It seems Moya is encouraging the stubbed responses to be part of the production app (this seems to be the case in [Eidolon](https://github.com/artsy/eidolon) as well).

I'm wondering why this is and if there's a way not include unnecessary json files in the production app? 

I thought about having a `stubbedResponseProvider` that would simply return empty `NSData`s in production but figured I'd try to understand why Moya is encouraging the other way first.

Thanks!

**Comment by ashfurrow** [comment]
This is a great question, thanks! It's not something I've personally had an issue with, but I can totally see the concerns. 

So, the rationale behind this decision is to make sure that people _have_ to define sample date to make testing easier / encourage testing. There's no way to define a requirement _only_ in a test target, so this was our solution. 

But it's not ideal for everyone. An empty `NSData()` would do the trick, but what if you wanted to use this for testing? Empty `NSData()` wouldn't work then. In that case, I'd take the JSON out of the Xcode target (so they're not shipped with the app) and instead of using `NSBundle` to load the JSON, use some other way to reference the Xcode. FBSnapshotTestCase does this using either environment variables:

```objc
[NSProcessInfo processInfo].environment[@"ENV_VAR_NAME"]
```

or by using `NSBundle`'s `resourcePath`:

```objc
[[NSBundle bundleForClass:self.class].resourcePath stringByAppendingPathComponent:@"FolderWithJSON"]
```

That way the code is loading the files directly for disk and not through `NSBundle`. This won't work if you're running tests on the simulator, though, so that's one potential downside.

Let me know what you think – I'd like to know what you think an optimum solution would look like, and how we could improve our documentation around this. Thanks again for opening the issue!

**Comment by hirad** [comment]
Thanks for the great response!

I asked this question because I was trying to keep test code/data completely out of the main code, so anything I suggest may not fit well with the "encourage testing" goal.

My initial hunch on this was that it has dependency injection written all over it. We need something to provide stubbed data. That can be empty in production, but must be available for tests - therefore, different dependencies.

Keeping in mind that I haven't *actually* used Moya yet (so I don't know how this meshes with it), my first idea was this: 

```swift
struct MyAPI {
    enum Target {
        case GetUser, GetFiles
    }
    
    private let target: Target
    private let sampleDataProvider: (Target -> NSData)
    
    private static func DefaultDataProvider(t: Target) -> NSData {
        return NSData()
    }
    
    init(_ aTarget: Target, sampleDataProvider provider: (Target -> NSData) = MyAPI.DefaultDataProvider) {
        target = aTarget
        sampleDataProvider = provider
    }
}

extension MyAPI: TargetType {
    /* These would all switch on self.target */
    var path: String { ... }
    var baseURL: NSURL { ... }
    var parameters: [String: AnyObject]? { ... }
    var method: Moya.Method { ... }

    var sampleData: NSData {
        return sampleDataProvider(self.target)
    }
}

let target = MyAPI(.GetUser)

let testTarget = MyAPI(.GetUser, sampleDataProvider: /* a closure that actually returns stubbed data */)
```

It's using a `struct` just because the `sampleDataProvider` needs to get stored somewhere. That's a drawback, along with the fact that, in tests, every instance of an API target needs to get its own `sampleDataProvider` at `init`.

Reading through the docs more (including the ["Advanced Use" section on Providers](https://github.com/Moya/Moya/blob/master/docs/Providers.md#advanced-use)), it seems to me that this kind of behaviour belongs in the provider itself (as opposed to the `TargetType`). We're already injecting all sorts of stuff in there - custom endpoint mapping, request mapping, etc. The provider could also take something like a `sampleDataProvider` and default it to return an empty `NSData` in production, but in tests, the user can provide their own `sampleDataProvider`.

I think with this all the test code can stay in tests, and the production code doesn't need to know about any stubbed responses.

Thoughts? Am I off my rockers?

**Comment by ashfurrow** [comment]
This is a really interesting idea, I like it. It takes away from the goal of encouraging testing at all costs, but that may be discouraging some users from trying Moya. And I'm pretty sure they'll just return `NSData()` anyway :wink: 

This is a pretty big breaking change that would pair well with #426 when that gets merged. I think we should be careful about it; I'd like to get feedback from @Moya/contributors on the following idea:

Move `sampleData` out of the `TargetType` and into a closure passed to the provider that returns sample data based on its parameter, a target. This would complicate how we [handle structs](https://github.com/Moya/Moya/pull/424), though... We can also consider moving this behaviour into the `stubClosure`, like:

```diff
-typealias StubClosure = TargetType -> Moya.StubBehavior
+ typealias StubClosure = TargetType -> (Moya.StubBehavior, Response)
```

And we could even make this parameter optional, and `nil` implies "never stub", which would simplify the provider a bit. Just an idea, trying not to get ahead of myself :wink:

**Comment by sunshinejr** [comment]
I like the idea of expanding `StubClosure` rather than passing it with provider as it is already big I would say (even tho we might not get any problems of the structs now as we'd chosen the simpler way of handling it). It also _feels right_ in `TargetType` (at least for me 😆).

**Comment by ashfurrow** [comment]
Any more discussion/action items on this? Or can we safely close?

**Comment by tbaranes** [comment]
Just wondering, is there a reason why @hirad suggestion did not been implemented? I'm joining him about moving `sampleData` to providers (as a closure) instead of keeping it in `TargetType`. As @hirad, I'd prefer to have my stubbed response only in the tests target instead of the app, but in the current implementation of Moya, I can't find a nice way to handle this (as the potential solutions described above).

Any thought about this?
