### ISSUE TITLE
Endpoint doesn't need to be generic

### ISSUE THREAD

**Issue by ashfurrow** [Moya/Moya#434]
If the `Endpoint` type isn't generic, users can build a non-generic provider that may be better-suited for their needs. 

Background:

Today, @jasl and I had a Skype call about #376 to discuss their fork of Moya that uses a far less generic-based approach: https://github.com/jasl/MoyaX There are some really cool ideas there, and I realized that by forcing `Endpoint` to be a generic restricts those ideas. There's no need for it to be generic, that I can think of.

Other ideas were a little more radical, and might not fit within Moya, but would make excellent library extensions. For example, the non-generic providers used in MoyaX help define more complex APIs involved in social network apps (other people have cited social network apps as a use case for using structs instead of enums, too).

Once we remove the generic `Endpoint` requirement, there are some other ideas we should consider borrowing from MoyaX:

- Make the backend (Alamofire) abstracted away so users can replace their own. This might be an interesting way to stub network calls instead, like having a "StubBackend" to stub requests. 
- I'm sure I missed some, @jasl please add the ones I missed.

This is a longer-term project, and Moya as it exists today is relatively stable. We need to be mindful about how we introduce changes like this to our existing users, and balance the trade-offs appropriately. 

Thanks again @jasl for your great ideas :cake:

**Comment by jasl** [comment]
Seems `Backend` should be `Strategy` more clearly.

The Moya current data flow is
`TargetType - endpointClosure -> Endpoint<T> - requestClosure -> NSURLRequest - plugins -> Alamofire's Request -> Cancellable`
Because of generic Endpoint, we can do some things like adding authentication headers for specified Target in `requestClosure`, I think that's why `Endpoint` needs be generic. @ashfurrow is this right?

If `Endpoint` becoming non-generic, how do we do the same thing? maybe moving this job to `TargetType` itself is a good choice, so MoyaX's flow is
`TargetType - TargetType#endpoint-> Endpoint -> Provider#willTransformToRequest -> NSMutableURLRequest - plugins - Backend -> Cancellable`

Besides, `Endpoint` is a Moya internal presentation of `TargetType`, I think there is no side effect and should keeping in a single thread, so changing `Endpoint` no need returns a new instance and It could be a `struct`.

After these changes, I think generic Provider is just for convenient.
I admit non-generic provider is a little radical, but If we have non-generic Provider first, we can easily wrapping it as generic provider but harder the other way.
In MoyaX, the generic Provider reused most of non-generic provider, so It's only [10 lines](https://github.com/jasl/MoyaX/blob/master/Source/Provider.swift#L53-L63).

**Comment by ashfurrow** [comment]
Going to close this and move discussion to #556.
