### ISSUE TITLE
casting Moya Error to NSError in .Falilure case causes Switch to be non-exhaustive

### ISSUE THREAD

**Issue by lkuczborski** [Moya/Moya#437]
Moya has it's own Error type. When you try to cast it to NSError inside .Failure case, switch suddenly becomes non-exhaustive forcing you to add:

```swift
default:
    break
````

**Comment by ashfurrow** [comment]
The problem looks like Moya vends its own [Error type](https://github.com/Moya/Moya/blob/4a834fcc96ed239d1f8da621c0ca4d16162d0a9d/Source/Error.swift#L3). It's an `ErrorType` so every cast to `NSError` will succeed, but I suspect the Swift compiler is getting confused. Try this:

```swift
case .Failure(let error):
    let nsError = error as NSError
```

Let me know :+1:

**Comment by sunshinejr** [comment]
Hey @lkuczborski! Thanks for reporting the issue! 🎉 

Although Moya's `Error` inherits from `ErrorType` and `NSError` also inherits from `ErrorType`, the cast from one to another is done by some bridging, because they aren't really connected other than the `ErrorType` protocol. So when you cast from `Moya.Error` to `NSError`, you get some really basic info and the associated type is gone. I'm guessing that the compiler is just confused, and it could be a bug, but I can't tell for sure. For now you can use `Moya.Error` property `nsError`. It might be removed in a future so you could copy the code and make your own extension instead.

**Comment by lkuczborski** [comment]
@ashfurrow This causes associated type to be gone and only basic info is preserved, just like @sunshinejr said. Making my own extension to be future safe seems like a good idea, thanks!

**Comment by sunshinejr** [comment]
Glad I could help! ✌️
