### ISSUE TITLE
swift 2.2 warning

### ISSUE THREAD

**Issue by paulz** [Moya/Moya#442]
Thank you for the awesome networking framework!

We have migrated to swift 2.2 and started to get this warning:

▸ Compiling Plugin.swift

⚠️  /Pods/Moya/Source/Moya.swift:192:40: curried function declaration syntax will be removed in a future version of Swift; use a single parameter list

    public final class func DelayedStub(seconds: NSTimeInterval)(_: Target) -> Moya.StubBehavior {
                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Would it be possible to workaround curried function or avoid the warning any other way? 
Somehow it comes multiple times in our build log on [travis-ci.com](https://travis-ci.com). 

Thank you!

**Comment by ashfurrow** [comment]
Thanks for the kind words! The fix for this would be to change the [DelayedStub](https://github.com/Moya/Moya/blob/84e02244b5d89971611f167bf25d629ce77b5a74/Source/Moya.swift#L192-L194) function to look like this:

```swift
public final class func DelayedStub(seconds: NSTimeInterval) -> (Target -> Moya.StubBehavior) {
    return { _ in .Delayed(seconds: seconds) }
}
```

I'm strapped for time at the moment, if someone else has the time to make + test this change, that'd be :100:

**Comment by colinta** [comment]
I can do this right now.

**Comment by colinta** [comment]
Moving conversation to #443
