### ISSUE TITLE
How to send more than one time the same parameter

### ISSUE THREAD

**Issue by VivienGiraud** [Moya/Moya#506]
Hi,

As I have no idea how the thing I want to do is called I failed to search it on the Internet.
Can you tell me how to send a parameter two times for example?
Like if I want to register a book, `Genre` can be `Science Fiction` and `Fantasy`.
So I need to do like:

``` swift
provider = MoyaProvider<TEST>()
provider.request(.Genre("Science Fiction"), .Genre(Fantasy)) { result in
    // do something with the result
}
```

But I don't think it's the right way to do.
Can someone understand what I mean?

Vivien

**Comment by petester42** [comment]
You can have two enum cases. One that takes a string and one that takes an array of strings.

**Comment by Miasma87** [comment]
Not sure to understand what you mean :/
Can you explain it with code please?

**Comment by sunshinejr** [comment]
Hey @Miasma87! What I think @petester42 meant, was to extend your `TargetType` to have 2 cases:

- First one for getting one genre from API:
```swift
case Genre(String)
```
- Second one for getting more than one (or to be precise, 0 or more) genres using array of strings:
```swift
case Genres([String])
```

But it depends if your API has an endpoint for getting more than one genre at a time. If not, I'm afraid Moya does not have built-in solution for that. Actually, it would be really tricky, because what happens if one request succeeds and one does not? We would need an array of result responses/errors or any other solution to handle this.

But what comes to my mind is that you could create an asynchronous queue and handle this by yourself. Or use reactive extensions for Moya, which would make that task significantly cleaner.

Hope it helps! 🐼

**Comment by BasThomas** [comment]
Have you been able to fix this, @Miasma87?

**Comment by Miasma87** [comment]
Sorry but we had to delay the use of Moya to one sprint in September due to bugs in our app.
Be sure that I will update this one once checked ! ;)

**Comment by BasThomas** [comment]
Do you have an update on this, @VivienGiraud? :)

**Comment by VivienGiraud** [comment]
Hi,
We had couple of troubles with our app (nothing related to Moya).  
We had to put aside our project so I can't update it unfortunately :/

**Comment by BasThomas** [comment]
No worries, thanks for the update nonetheless!

**Comment by scottrhoyt** [comment]
Since there hasn't been any activity on this thread for some time, I am going to go ahead and close it. Please re-open or create a new issue if you would like to discuss further. Thanks.
