### ISSUE TITLE
How to make a request with duplicated parameter keys?

### ISSUE THREAD

**Issue by nikita-leonov** [Moya/Moya#528]
Moya target expected all request parameters to have unique keys. This requirement is not clearly specified HTTP requirement and pretty often disregarded by various frameworks and APIs developers. So sometimes we do need to send request like following http://someserver.com/api/?filter=a&filter=b while Moya due to current interface limitations is not able to do so. Is there any quick way to workaround it?

**Comment by nikita-leonov** [comment]
It seems I can workaround it with Plugin with willSend implementation. It would be hard to actually fix it in Moya, as Alamofire underlaying implementation does expect Dictionary too.

**Comment by nikita-leonov** [comment]
Ok, apparently Plugins are not able to modify requests due to following issue https://github.com/Moya/Moya/issues/326 Need to find another workaround.

**Comment by nikita-leonov** [comment]
Augmenting of request by overriding `urlRequest` property for endpoint is also impossible, since it is defined in extension :(

**Comment by nikita-leonov** [comment]
It seem that the best option possible now is defying of requestClosure and intercept NSURLRequest there.

**Comment by nikita-leonov** [comment]
Since there is no way to find out Endpoint Target value within RequestClosure, I was forced to match response URLs and define override behavior based on a URL patterns. Looks like a complete hack :(

**Comment by ashfurrow** [comment]
A request with duplicated parameter keys? I've never seen a server require those before, since query string parameters are usually referenced as a dictionary, and can't handle duplicate keys. I have seen arrays specified as `?filter[]=a&filter[]=b`, is that what you're looking for?

It's possible to get around this by doing your own custom parameter encoding (since we rely on Alamofire's, which has this limitation of treating params as a dictionary). Here's [an example of using custom parameter encoding](https://github.com/Moya/Moya/blob/38b0bda890b7b4598552a353b3f8db4248c37d6e/docs/Examples/ArrayAsRootContainer.md) that you should be able to modify for your server requirements. Let us know how it goes.

**Comment by nikita-leonov** [comment]
Yes, arrays specified as you described actually are duplicated parameter keys. This is what I was trying to solve. Custom endpoint mapping with a custom encode parameters for the scenario where duplicated parameter keys required helped. Thanks for a guidance. 

Meanwhile the amount of code required to handle the case that is correct use case for APIs is a little bit disappointing. Should I keep this issue closed or open for further discussion how possible to address this case?

**Comment by ashfurrow** [comment]
I'm glad – I think if you just pass the array as a a parameter, it should "just work." Alamodome detects arrays and uses that query string format.

**Comment by colinta** [comment]
OK to close?

**Comment by nikita-leonov** [comment]
Yes, it was fine to close. Sorry next time I will close myself.
