### ISSUE TITLE
Clean up Milestones

### ISSUE THREAD

**Issue by ashfurrow** [Moya/Moya#539]
Similar to #538, we have two milestones:

<img width="1014" alt="screen shot 2016-07-12 at 8 23 05 pm" src="https://cloud.githubusercontent.com/assets/498212/16787979/d4cada46-486e-11e6-8032-d7fda4e955da.png">

We haven't really been using this, or at least I haven't. If they are used, and especially if they're useful, let's document them somewhere and make sure they're used.

**Comment by sunshinejr** [comment]
@ashfurrow About **Documentation** milestone, it is used for ongoing documentation update that is mostly done. I think it is fine to keep it till we polish everything. I don't know, however, about the **Long Term** one. We might check them out because the update dates of these issues are relatively old. 

About documenting it, would it be okay to add a paragraph in [Readme#Contributing](https://github.com/Moya/Moya#contributing) about using milestones (and listing current ones with description)?

**Comment by ashfurrow** [comment]
Do you see the documentation work you've been doing as an ongoing project, or something that will be completed one day? It might make sense as an issue label, up to you. The readme idea sounds great!

**Comment by sunshinejr** [comment]
I was rather thinking about finishing the current issues we had with docs, reach the milestone, close it and go from there (with issue labels for instance, like you said). What do you think about it?

**Comment by ashfurrow** [comment]
If we're going to switch to issue labels anyway, I'm in favour of switching now.

**Comment by sunshinejr** [comment]
Sure! Makes sense. How about the **Long Term** milestone? I'm just wondering if we need to actually document it if we resign from **Documentation**.

**Comment by ashfurrow** [comment]
Yeah, I'm thinking we should just close both and not use milestones. We can always start using them in the future if circumstances change.

**Comment by sunshinejr** [comment]
Right! On it :)
