### ISSUE TITLE
Nothing about multipart file uploads in 7.0.0 release notes?

### ISSUE THREAD

**Issue by AndrewSB** [Moya/Moya#546]
Didn't see anything about #483 in 7.0.0's [notes](https://github.com/Moya/Moya/releases/tag/7.0.0), was that on purpose?

**Comment by ashfurrow** [comment]
Hmm, looks like an oversight. Want to send a pull request with the added entry?

**Comment by orta** [comment]
It might be worth adding Danger's CHANGELOG as a fail back, even in this case it was missed, but the fail was legit:

<img width="788" alt="screen shot 2016-07-14 at 12 31 38" src="https://cloud.githubusercontent.com/assets/49038/16847420/0029f360-49bf-11e6-8d77-00d9f238e5ba.png">

**Comment by ashfurrow** [comment]
I think we would have noticed the danger message if it had run, but something went wrong on that build:

<img width="659" alt="screen shot 2016-07-14 at 12 36 13 pm" src="https://cloud.githubusercontent.com/assets/498212/16847560/a5d62ee6-49bf-11e6-9814-47a41b74ff62.png">

Which is on me, I should have re-run the build or fixed Danger. I think that pull request had just taken so long to get tot hat point, I was too impatient to merge.

**Comment by orta** [comment]
I took that image from the PR: https://github.com/Moya/Moya/pull/483#issuecomment-230908591 - it must have got fixed on a rebase or something

**Comment by ashfurrow** [comment]
Yeah, what I mean is that if Danger had had a chance to run and fail due to a missing changelog, the human merging (me) should have asked for one. But because I ignored the Danger failure (because it wasn't working), I also ignored the previous comment Danger had made about this missing changelog. I guess I assumed it had been added at some point. 

I agree we should probably re-think how we treat missing changelog entries. What sort of heuristic do you reckon should we use? 

- Any swift files changed?
- A certain number of .swift lines added/removed/changed?

**Comment by orta** [comment]
Ah, yeah, on Danger we [check for any](https://github.com/danger/danger/blob/master/Dangerfile#L4-L5) lib files:

```ruby
has_app_changes = !git.modified_files.grep(/lib/).empty?
has_test_changes = !git.modified_files.grep(/spec/).empty?
```

You could do the same for `Source` and `Demo/Tests`:

```ruby
has_app_changes = !git.modified_files.grep(/Source/).empty?
has_test_changes = !git.modified_files.grep(/Demo\/Tests/).empty?
```

_* disclaimer, I'm not great with regexes_

**Comment by ashfurrow** [comment]
Sounds good. I'll send a PR, thanks for bringing this up again Orta.

**Comment by AndrewSB** [comment]
thanks for taking care of this @ashfurrow 😄
