### ISSUE TITLE
[Question] Beta tag for podspec use

### ISSUE THREAD

**Issue by juliengdt** [Moya/Moya#641]
Hello,

It could be cool to have a `7.1.0-beta` tag linked on the `swift-3.0` branch; 
this could help poeple who is waiting for a swift 3 Moya dependency in their podspec.

Cheers from France

**Comment by BasThomas** [comment]
Take a look at #627. Does that help? :)

**Comment by juliengdt** [comment]
@BasThomas I talked about dependencies into podspec not into podfile: you can't specify url and branch into podspec, that's why a ```beta```tag could be cool for beta ones

**Comment by BasThomas** [comment]
Ah, of course. Sorry!

**Comment by ashfurrow** [comment]
Great question @juliengdt. The solution is to specify the branch in your Podfile; if you're writing a library that depends on Moya, I'm afraid the best solution is to document that they will need to do that in their own Podfiles. 

I'm reluctant to tag a release because we're just not ready with Swift 3 support yet, especially around our ReactiveCocoa extensions. Does that answer your question?

**Comment by juliengdt** [comment]
@ashfurrow I'm not sure but if:

* A need B version 1.0
* In my Podfile I put
    * A
    * B version 2.0

There is no pod conflict ? 💭

**Comment by ashfurrow** [comment]
Basically yeah, you're basically telling CocoaPods that you want to override that version of B. It's worked for me in the past, if it's a problem we can always tag maybe like an alpha?

**Comment by juliengdt** [comment]
Hi, 

Ok i will try this out !

**Comment by ashfurrow** [comment]
Should be resolved by our new use of a 8.0.0 beta tag, can you verify?

**Comment by juliengdt** [comment]
resolved yes

**Comment by ashfurrow** [comment]
Fab, thanks!
