### ISSUE TITLE
Remove Demo.xcodeproj, move tests into the root directory

### ISSUE THREAD

**Issue by AndrewSB** [Moya/Moya#696]
I realized this when looking at #668, Is there a reason our tests are inside the `Demo/` dir? I had trouble finding them, and it feels strange that I can't run tests while Im working on Source in `Moya.xcodeproj`

 IMHO it makes sense to pull them out into a `Tests/` directory, and move all the targets in `Demo.xcodeproj` to `Moya.xcodeproj`, making it so the `Demo/` directory just contains the code required run the demo app

**Comment by ashfurrow** [comment]
Great question. The tests have been in the Demo directory just because of convenience, sometimes you need to run the code in a real app's lifecycle. I'm happy to move them into a `/Tests` directory, but would prefer that they stay integrated with CocoaPods. If we _did_ move tests out of Carthage, we would need to do a `pod lib lint` on CI to make sure we don't break CocoaPods integration.

**Comment by AndrewSB** [comment]
If the move is possible, I think we should do it. The directory structure with `Source/`, `Demo/`, `Test/` will also play very nicely with swift package manager once we support it.

I'll start a PR, but I'm not sure how to do the `pod lib lint` on CI. Can you help out with that when you have some time?

**Comment by AndrewSB** [comment]
Created #698
