### ISSUE TITLE
Mystery in building targets or solving cocoapods and carthage dependencies.

### ISSUE THREAD

**Issue by lolgear** [Moya/Moya#707]
I looked at `.xcodeproj` targets.

As I understand, framework / target depends on RxSwift or ReactiveSwift ( choose either ).

How do you solve dependency for cocoapods and for carthage simultaneously?

**Comment by petester42** [comment]
We don't solve it for both at the same time. For Carthage we use the xcodeproj and for cocoapods we use the podspec. 

For cocoapods you don't need a xcodeproj since we just need to define a file that says what our dependencies are, where the source files are etc. Later when a user uses cocoapods to install our library it creates a target based on the settings we provide.

**Comment by lolgear** [comment]
@petester42 but there are ReactiveSwift and RxSwift in some targets.

How do you build them in case of `carthage update`.
As I know, you can not tell `carthage update` about dependencies. It will download them and put in one pile. Only hosted app can make dependencies.

If your target has a dependency, it should make tricks with them to be carthage-compatible.
( As I mentioned above, ReactiveSwift or RxSwift )

So, how do you specify an 'optional' dependency from ReactiveSwift and from RxSwift for `carthage update`?

**Comment by AndrewSB** [comment]
Hey @lolgear! I believe you're talking about some changes that I made last month.

https://github.com/Moya/Moya/pull/563 is the pull request that suggested those changes, and the comments there go into the rationale behind the choices I made, and how it solves the dependency management mystery 🎩 

I'm around if you have any follow up questions 👊

**Comment by lolgear** [comment]
@AndrewSB thank you for swift reaction! 
Not sure, it is a fat pull request. 
However, you use compiler directives to determine building choice. That's sound good.

However, Moya, as I understand, uses Alamofire under the hood ( dependency ).

Also there are several Moya versions - ReactiveMoya ( + ReactiveSwift ) and RxMoya ( RxSwift ).
So different version of Moya uses different set of dependencies.

Summing up my knowledge:

Moya has core that uses Alamofire.
ReactiveMoya uses Moya and ReactiveSwift.
RxMoya uses Moya and RxSwift.

Strange for Carthage.

Carthage idiom is 'module without dependencies'. All dependencies are linked together in your app ( final point ).

So, how do you make your scheme for Carthage?

ReactiveMoya: ReactiveSwift + Moya
Moya: Core + Alamofire
RxMoya: RxSwift + Moya

Cocoapods could solve this dependency tree in a several lines. 
Carthage can not. ( My knowledge ).

**Comment by petester42** [comment]
We don't make the scheme for Carthage. We just make it a normal xcode scheme. We use Carthage to download the dependencies so that our schemes will compile by specifying a Cartfile. 

So what happens when someone uses Carthage to get Moya for their app. Carthage builds all Moya dependencies (by looking at all of the cartfile) and Moya itself (by looking at the xcodeproj). The developer now has to add Moya and all it's dependencies to their own scheme. You can't just include Moya, you have to include all the dependencies of the Moya version you want to use as well.

**Comment by AndrewSB** [comment]
Yup, @petester42 is completely right.
By including the line `github "Moya/Moya"` in a Cartfile, it builds all three of the shared targets (Moya, RxMoya, and ReactiveMoya), as well as all of the dependencies, and then you choose which frameworks you want to drag into your linked frameworks

**Comment by lolgear** [comment]
@petester42 @AndrewSB and also Moya uses Carthage/Build/<Module> in **Framework Search Paths**. It's clear now, thanks!

**Comment by orta** [comment]
👍
