### ISSUE TITLE
Different Params encoding within one Endpoint?

### ISSUE THREAD

**Issue by zhigang1992** [Moya/Moya#712]
I know this is wrong, but it does happen. :(

Currently, we have these properties for a target.

```swift
public protocol TargetType {
    var baseURL: NSURL { get }
    var path: String { get }
    var method: Moya.Method { get }
    var parameters: [String: AnyObject]? { get }
    var sampleData: NSData { get }
}
```

Is there a easy way to extend this list to include `ParameterEncoding` as well?

Thanks

**Comment by sunshinejr** [comment]
Hey! I know the feeling so don't worry about it 👊 

You can extend `TargetType` protocol with `ParameterEncoding` parameter, then in the `endpointClosure` use the `parameterEncoding` from target. [Here](https://github.com/sunshinejr/FlexibleMoya/blob/c33f9b9bbeddab2776de33f08d802660dab3ea4b/FlexibleMoya/Networking/Utils/MoyaUtils.swift#L14) you have example how I did it with `authToken` type, just instead of `authToken` use `parameterEncoding` in the `Endpoint` init. 

More on the `endpointClosure` you can also find [here](https://github.com/Moya/Moya/blob/master/docs/Endpoints.md#from-target-to-endpoint).

Hope it helps! If you have more questions or something is unclear, shoot 🙂

**Comment by zhigang1992** [comment]
wow,  sweet. 

Right on... Thank you.. 😄 

🍻
