### ISSUE TITLE
Fix CI

### ISSUE THREAD

**Issue by ashfurrow** [Moya/Moya#752]
CI is broken (see https://circleci.com/gh/Moya/Moya/778 ) with the following error:

```
The requested device could not be found because multiple devices matched the request.

Available destinations for the "MoyaTests-tvOS" scheme:
	{ platform:tvOS Simulator, id:48B0E1AB-F5EB-40FB-9372-A16B93349B12, OS:10.0, name:Apple TV 1080p }
	{ platform:tvOS Simulator, id:CFB6004F-16F9-49B4-A117-CAFBCC0CE7CB, OS:10.0, name:Apple TV 1080p }
```

I've not seen this before, don't have a tonne of time to look into this right now. Help would be welcome.

**Comment by pedrovereza** [comment]
That's an [issue with Circle CI](https://discuss.circleci.com/t/multiple-ios-simulators-available-for-single-os-device-configurations/7854)

As a workaround, instead of calling `xcodebuild` with `-destination name='Apple TV 1080p'` we can use one of the ids in the error message: `-destination id=48B0E1AB-F5EB-40FB-9372-A16B93349B12`

But as the folks from Circle CI are already working on it, maybe we just wait a bit?

**Comment by ashfurrow** [comment]
Thanks for looking into that @pedrovereza , let's wait and see 👍

**Comment by pedrovereza** [comment]
Seems like it won't be fixed until [next week](https://discuss.circleci.com/t/multiple-ios-simulators-available-for-single-os-device-configurations/7854/3?) 😞 

Should we go ahead and change the Rakefile to use ids instead of names?

**Comment by ashfurrow** [comment]
Sounds like a plan, thanks!

**Comment by pedrovereza** [comment]
Closing this one, we can follow up in #757
