### ISSUE TITLE
Remove manual CocoaPods Caching

### ISSUE THREAD

**Issue by ashfurrow** [Moya/Moya#755]
Circle is rolling this out: https://discuss.circleci.com/t/downloading-cocoapods-specs-from-s3-instead-of-git/7856

**Comment by pedrovereza** [comment]
From the link you posted:
>The feature has been automatically enabled for all customers who use our **inferred iOS dependency commands**. If you are using iOS inference for the dependencies step, you will notice a new step, Fetch CocoaPods specs, in your build

We can't use this feature yet as we're overriding the steps in [circle.yml](https://github.com/Moya/Moya/blob/master/circle.yml#L8) 😕 

Details on the `override` option from Circle CI [docs](https://circleci.com/docs/configuration/#phases):
> override: commands run instead of CircleCI’s inferred commands

Feels like we'll have to wait until they roll this out to everyone.

**Comment by ashfurrow** [comment]
Hmm, that's too bad. Good catch 👍

**Comment by AndrewSB** [comment]
Yeah, that is unfortunate that it only works with the inferred dependency commands 😞.

I wonder if we'd be able to use circle's inferred dependency installation instead of overriding with our custom commands in https://github.com/Moya/Moya/blob/master/circle.yml#L8.

I think https://github.com/Moya/Moya/pull/698 is a good candidate for a solution where we can use a CI platform's inferred dependency installation, and potentially testing.
