### ISSUE TITLE
A MoyaProvider variant which does not have a generic <Target> parameter?

### ISSUE THREAD

**Issue by AndrewSB** [Moya/Moya#830]
@manas-chaudhari mentioned something interesting here: https://github.com/Moya/Moya/issues/823#issuecomment-265458718

Let's use this issue to discuss whether we can implement what he was trying to do 😄

**Comment by AndrewSB** [comment]
closing this for now. @manas-chaudhari: please do re-open this if you're interested in getting this added to Moya

**Comment by manas-chaudhari** [comment]
Yes, I am interested in getting this added to Moya. Let me summarize the points.

Current implementation of `MoyaProvider` has a template variable `<Target>` at the class level. Because of this, one instance of `MoyaProvider` can work with only one type of target. 

Using `MultiTarget`, we have created a wrapper so that a single instance can be used for different inner `TargetType`s. This works when there are no associated types involved in enums.

In order to extend Moya's functionality, it is sometimes necessary to use associated types by extending the `TargetType` protocol. One use case is to abstract deserialization, so that MoyaProvider can return an `Observable<ModelType>`, where `ModelType` is the associatedtype. This has been discussed in https://github.com/Moya/Moya/issues/823#issuecomment-265458718.

The idea is to build a `MoyaProvider` variant which does not have any template variable at the class level, but instead at the `request` method level. 

```func request<T: TargetType>(request: T, completion: Moya.Completion)```

This would allow basic usage and also allow Moya consumers to add extensions like:

```func requestDecoded<T: DecodableTargetType>(request: T, completion: (_ result: Result<T.ResultType, Moya.Error>) -> ())```
or simply
```func requestDecoded<T: DecodableTargetType>(request: T) -> Observable<T.ResultType>```

I don't have access to reopen the issue. @AndrewSB Can you do this.

**Comment by AndrewSB** [comment]
Sounds interesting @manas-chaudhari, I'm having a little trouble understanding your example though, are you saying that if I wanted to request my user model, for example, I'd do `provider.request<UserModel>(.me, completion...)`? In my opinion, that doesn't add much more to `provider.request(.me).map(UserModel.init)`.

Would you like to make a PR to implement your idea? I think starting out with amending the docs would be the easiest for me to understand exactly what you're suggesting, and for the contributors to talk about (see https://github.com/Moya/Moya/pull/762 for an example). If we can get enough people saying they like your idea, we would be able to merge this in 😄

**Comment by manas-chaudhari** [comment]
Yes, I would love to implement this. Amending the docs is a good idea. I'll first update one of the examples doc assuming that this MoyaProvider exists. 

In the above example, `DecodableTargetType` extends `TargetType`.
```
protocol DecodableTargetType: Moya.TargetType {
    associatedType ResultType: SomeJSONDecodableProtocolConformance
}
```

Perhaps a specific example would help.
```
enum UserApi : DecodableTargetType {
    case get(id: Int)
    case update(id: Int, name: String)
    ...

    var baseURL: URL { ... }
    var path: String { switch self ... }
    var method: Moya.Method { ... }
    
    typealias ResultType = UserModel
}
```

To invoke the api
```
let user = provider.request(UserApi.get(id: 1)) 
// The type for user is Observable<UserModel>

let user: Observable<SomethingElse> = provider.request(UserApi.get(id: 1))
// This doesn't compile. Thus, you get a compile time check for ensuring the right type
```

Thus, the generic parameter `UserApi` is implicitly derived from the Api instance provided. The return type is also implicitly derived from the Api instance provided. The beauty of this is that the return type changes (implicitly) based on the argument that you pass to the function.

In case of `provider.request(.me).map(UserModel.init)`, this will fail at runtime if an incorrect model is passed.

I hope this makes it clear. The content for the updated doc would also be on these lines.

**Comment by AndrewSB** [comment]
Sounds great @manas-chaudhari, looking forward to checking out the updated docs 😄

**Comment by AndrewSB** [comment]
Closing this in favor of #910 😄
