### ISSUE TITLE
Consider breaking Rx and ReactiveSwift extensions into separate repositories

### ISSUE THREAD

**Issue by BasThomas** [Moya/Moya#908]
As discussed in #907

**Comment by bjarkehs** [comment]
While I think it could be nice that you don't automatically build Rx and ReactiveSwift extensions out-of-the-box with Carthage, then I believe the issues can be mitigated in other ways. 

One way could be caching `Carthage/Build` and/or `Carthage/Checkout`. 

But another way entirely could be to run it with `carthage boostrap --no-build`, which would postpone building to when the project is being compiled. I'm not entirely sure how well this option works with Moya, since I haven't personally tried it too much. I did some tests with it earlier today, but failed to get it to compile on CI.

**Comment by scottrhoyt** [comment]
I was more concerned with this before RxSwift and ReactiveSwift were reliably offering framework downloads. I think it is less of an issue now. There are still some benefits to not expanding our users' dependency graphs, but I think those are outweighed by the additional maintenance and release coordination headaches that will come will the 3 repo approach. I'd love to see carthage offer an option similar to a subspec (especially since it is possible with SPM), but I recognize that is going against the grain of carthage's simplicity.

**Comment by AndrewSB** [comment]
Yup, I agree with @scottrhoyt, it seems like a non issue now. 

Feel free to re-open if anyone would like to go into this further 😄

**Comment by edulpn** [comment]
I'm having issues when running ```carthage update --platform iOS``` with Moya in my Cartfile. Carthage hangs while fetching ReactiveSwift, CPU spikes to 100% and it will freeze up the entire machine unless I kill the process. Commenting Moya on the Cartfile makes it work, but locks me outside of my networking...

**Comment by AndrewSB** [comment]
This sounds like a Carthage issue. If you post on their repo, they’ll be
able to help you troubleshoot your Carthage
