### ISSUE TITLE
How to cache the get request manually?

### ISSUE THREAD

**Issue by shuijinliuxi** [Moya/Moya#976]
Our server not return the "Cache-Control ", so I want to use manually `URLCache` to cache the request, but I can not get the `URLRequest` with Moya.

**Comment by scottrhoyt** [comment]
@shuijinliuxi, you have 2 options for getting to the `URLRequest`:

* Utilize a custom `RequestClosure` in your provider to construct the request with any modifications needed.
* Create a `PluginType` that uses the `prepare` method to make any modifications to the `URLRequest` and add that to your provider.

Also if you need to modify the caching policy, you can construct an `Alamofire` `SessionManager` with a custom `URLSession` using a `URLSessionConfiguration` that modifies the caching policy to your liking. This can then be given to a `MoyaProvider` to use instead of the default. But you might be fine with the defaults as well.

**Comment by freemansion** [comment]
I'm had the same issue recently. I solved it writing Moya plugin.
If anyone still interested, below is working code:

```swift
protocol CachePolicyGettable {
    var cachePolicy: URLRequest.CachePolicy { get }
}

final class CachePolicyPlugin: PluginType {
    func prepare(_ request: URLRequest, target: TargetType) -> URLRequest {
        if let cacheableTarget = target as? CachePolicyGettable {
            var mutableRequest = request
            mutableRequest.cachePolicy = cacheableTarget.cachePolicy
            return mutableRequest
        }
        return request
    }

}

extension NetworkApiService: CachePolicyGettable {
    var cachePolicy: URLRequest.CachePolicy {
        switch self {
        case .userProfile:
            return .returnCacheDataElseLoad
        default:
            return .useProtocolCachePolicy
        }
    }
}
```

Also, if you want to specify the way of storing your data (in-memory capacity, disk capacity) according your needs, you have to pass `URLCache` object when your `URLSessionConfiguration` has been created.
