### ISSUE TITLE
RSS

### ISSUE THREAD

**Issue by startupthekid** [Moya/Moya#997]
What RSS capabilities does Moya have? Right now I'm using https://github.com/AdeptusAstartes/AlamofireRSSParser but I'd prefer Moya because of the ReactiveSwift support. If downloading and parsing RSS feeds isn't a feature, is it on the roadmap?

**Comment by scottrhoyt** [comment]
Handling object deserialization in general has been discussed, but currently is on the roadmap per se. So I don't think deserializing XML and parsing that into an RSS model is in the near future.

That being said, I took a look the library you referenced and I don't think it would be terribly hard to port it to Moya. 90% of the code would be reusable--you would just need to write the extensions for `Moya.Response` which should be pretty straightforward. I think if you were interested in that, it could be a very valuable addition to our community extensions.

Another option you have is to extend Alamofire with ReactiveSwift--I'd be surprised if such a library doesn't already exist. That also should be straightforward, especially since Alamofire already uses a `Result`-like pattern.

**Comment by sunshinejr** [comment]
I'm gonna close this issue due to inactivity, but feel free to reopen whenever.
